package com.atguigu.bean;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class AddressExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table address
     *
     * @mbg.generated Thu Oct 18 15:28:41 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table address
     *
     * @mbg.generated Thu Oct 18 15:28:41 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table address
     *
     * @mbg.generated Thu Oct 18 15:28:41 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address
     *
     * @mbg.generated Thu Oct 18 15:28:41 CST 2018
     */
    public AddressExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address
     *
     * @mbg.generated Thu Oct 18 15:28:41 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address
     *
     * @mbg.generated Thu Oct 18 15:28:41 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address
     *
     * @mbg.generated Thu Oct 18 15:28:41 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address
     *
     * @mbg.generated Thu Oct 18 15:28:41 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address
     *
     * @mbg.generated Thu Oct 18 15:28:41 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address
     *
     * @mbg.generated Thu Oct 18 15:28:41 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address
     *
     * @mbg.generated Thu Oct 18 15:28:41 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address
     *
     * @mbg.generated Thu Oct 18 15:28:41 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address
     *
     * @mbg.generated Thu Oct 18 15:28:41 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address
     *
     * @mbg.generated Thu Oct 18 15:28:41 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table address
     *
     * @mbg.generated Thu Oct 18 15:28:41 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Integer value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Integer value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Integer value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Integer value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Integer value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Integer> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Integer> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Integer value1, Integer value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andSexIsNull() {
            addCriterion("sex is null");
            return (Criteria) this;
        }

        public Criteria andSexIsNotNull() {
            addCriterion("sex is not null");
            return (Criteria) this;
        }

        public Criteria andSexEqualTo(String value) {
            addCriterion("sex =", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotEqualTo(String value) {
            addCriterion("sex <>", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexGreaterThan(String value) {
            addCriterion("sex >", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexGreaterThanOrEqualTo(String value) {
            addCriterion("sex >=", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexLessThan(String value) {
            addCriterion("sex <", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexLessThanOrEqualTo(String value) {
            addCriterion("sex <=", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexLike(String value) {
            addCriterion("sex like", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotLike(String value) {
            addCriterion("sex not like", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexIn(List<String> values) {
            addCriterion("sex in", values, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotIn(List<String> values) {
            addCriterion("sex not in", values, "sex");
            return (Criteria) this;
        }

        public Criteria andSexBetween(String value1, String value2) {
            addCriterion("sex between", value1, value2, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotBetween(String value1, String value2) {
            addCriterion("sex not between", value1, value2, "sex");
            return (Criteria) this;
        }

        public Criteria andAgeIsNull() {
            addCriterion("age is null");
            return (Criteria) this;
        }

        public Criteria andAgeIsNotNull() {
            addCriterion("age is not null");
            return (Criteria) this;
        }

        public Criteria andAgeEqualTo(Integer value) {
            addCriterion("age =", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeNotEqualTo(Integer value) {
            addCriterion("age <>", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeGreaterThan(Integer value) {
            addCriterion("age >", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeGreaterThanOrEqualTo(Integer value) {
            addCriterion("age >=", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeLessThan(Integer value) {
            addCriterion("age <", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeLessThanOrEqualTo(Integer value) {
            addCriterion("age <=", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeIn(List<Integer> values) {
            addCriterion("age in", values, "age");
            return (Criteria) this;
        }

        public Criteria andAgeNotIn(List<Integer> values) {
            addCriterion("age not in", values, "age");
            return (Criteria) this;
        }

        public Criteria andAgeBetween(Integer value1, Integer value2) {
            addCriterion("age between", value1, value2, "age");
            return (Criteria) this;
        }

        public Criteria andAgeNotBetween(Integer value1, Integer value2) {
            addCriterion("age not between", value1, value2, "age");
            return (Criteria) this;
        }

        public Criteria andAreaId1IsNull() {
            addCriterion("area_id1 is null");
            return (Criteria) this;
        }

        public Criteria andAreaId1IsNotNull() {
            addCriterion("area_id1 is not null");
            return (Criteria) this;
        }

        public Criteria andAreaId1EqualTo(String value) {
            addCriterion("area_id1 =", value, "areaId1");
            return (Criteria) this;
        }

        public Criteria andAreaId1NotEqualTo(String value) {
            addCriterion("area_id1 <>", value, "areaId1");
            return (Criteria) this;
        }

        public Criteria andAreaId1GreaterThan(String value) {
            addCriterion("area_id1 >", value, "areaId1");
            return (Criteria) this;
        }

        public Criteria andAreaId1GreaterThanOrEqualTo(String value) {
            addCriterion("area_id1 >=", value, "areaId1");
            return (Criteria) this;
        }

        public Criteria andAreaId1LessThan(String value) {
            addCriterion("area_id1 <", value, "areaId1");
            return (Criteria) this;
        }

        public Criteria andAreaId1LessThanOrEqualTo(String value) {
            addCriterion("area_id1 <=", value, "areaId1");
            return (Criteria) this;
        }

        public Criteria andAreaId1Like(String value) {
            addCriterion("area_id1 like", value, "areaId1");
            return (Criteria) this;
        }

        public Criteria andAreaId1NotLike(String value) {
            addCriterion("area_id1 not like", value, "areaId1");
            return (Criteria) this;
        }

        public Criteria andAreaId1In(List<String> values) {
            addCriterion("area_id1 in", values, "areaId1");
            return (Criteria) this;
        }

        public Criteria andAreaId1NotIn(List<String> values) {
            addCriterion("area_id1 not in", values, "areaId1");
            return (Criteria) this;
        }

        public Criteria andAreaId1Between(String value1, String value2) {
            addCriterion("area_id1 between", value1, value2, "areaId1");
            return (Criteria) this;
        }

        public Criteria andAreaId1NotBetween(String value1, String value2) {
            addCriterion("area_id1 not between", value1, value2, "areaId1");
            return (Criteria) this;
        }

        public Criteria andAreaId2IsNull() {
            addCriterion("area_id2 is null");
            return (Criteria) this;
        }

        public Criteria andAreaId2IsNotNull() {
            addCriterion("area_id2 is not null");
            return (Criteria) this;
        }

        public Criteria andAreaId2EqualTo(String value) {
            addCriterion("area_id2 =", value, "areaId2");
            return (Criteria) this;
        }

        public Criteria andAreaId2NotEqualTo(String value) {
            addCriterion("area_id2 <>", value, "areaId2");
            return (Criteria) this;
        }

        public Criteria andAreaId2GreaterThan(String value) {
            addCriterion("area_id2 >", value, "areaId2");
            return (Criteria) this;
        }

        public Criteria andAreaId2GreaterThanOrEqualTo(String value) {
            addCriterion("area_id2 >=", value, "areaId2");
            return (Criteria) this;
        }

        public Criteria andAreaId2LessThan(String value) {
            addCriterion("area_id2 <", value, "areaId2");
            return (Criteria) this;
        }

        public Criteria andAreaId2LessThanOrEqualTo(String value) {
            addCriterion("area_id2 <=", value, "areaId2");
            return (Criteria) this;
        }

        public Criteria andAreaId2Like(String value) {
            addCriterion("area_id2 like", value, "areaId2");
            return (Criteria) this;
        }

        public Criteria andAreaId2NotLike(String value) {
            addCriterion("area_id2 not like", value, "areaId2");
            return (Criteria) this;
        }

        public Criteria andAreaId2In(List<String> values) {
            addCriterion("area_id2 in", values, "areaId2");
            return (Criteria) this;
        }

        public Criteria andAreaId2NotIn(List<String> values) {
            addCriterion("area_id2 not in", values, "areaId2");
            return (Criteria) this;
        }

        public Criteria andAreaId2Between(String value1, String value2) {
            addCriterion("area_id2 between", value1, value2, "areaId2");
            return (Criteria) this;
        }

        public Criteria andAreaId2NotBetween(String value1, String value2) {
            addCriterion("area_id2 not between", value1, value2, "areaId2");
            return (Criteria) this;
        }

        public Criteria andAreaId3IsNull() {
            addCriterion("area_id3 is null");
            return (Criteria) this;
        }

        public Criteria andAreaId3IsNotNull() {
            addCriterion("area_id3 is not null");
            return (Criteria) this;
        }

        public Criteria andAreaId3EqualTo(String value) {
            addCriterion("area_id3 =", value, "areaId3");
            return (Criteria) this;
        }

        public Criteria andAreaId3NotEqualTo(String value) {
            addCriterion("area_id3 <>", value, "areaId3");
            return (Criteria) this;
        }

        public Criteria andAreaId3GreaterThan(String value) {
            addCriterion("area_id3 >", value, "areaId3");
            return (Criteria) this;
        }

        public Criteria andAreaId3GreaterThanOrEqualTo(String value) {
            addCriterion("area_id3 >=", value, "areaId3");
            return (Criteria) this;
        }

        public Criteria andAreaId3LessThan(String value) {
            addCriterion("area_id3 <", value, "areaId3");
            return (Criteria) this;
        }

        public Criteria andAreaId3LessThanOrEqualTo(String value) {
            addCriterion("area_id3 <=", value, "areaId3");
            return (Criteria) this;
        }

        public Criteria andAreaId3Like(String value) {
            addCriterion("area_id3 like", value, "areaId3");
            return (Criteria) this;
        }

        public Criteria andAreaId3NotLike(String value) {
            addCriterion("area_id3 not like", value, "areaId3");
            return (Criteria) this;
        }

        public Criteria andAreaId3In(List<String> values) {
            addCriterion("area_id3 in", values, "areaId3");
            return (Criteria) this;
        }

        public Criteria andAreaId3NotIn(List<String> values) {
            addCriterion("area_id3 not in", values, "areaId3");
            return (Criteria) this;
        }

        public Criteria andAreaId3Between(String value1, String value2) {
            addCriterion("area_id3 between", value1, value2, "areaId3");
            return (Criteria) this;
        }

        public Criteria andAreaId3NotBetween(String value1, String value2) {
            addCriterion("area_id3 not between", value1, value2, "areaId3");
            return (Criteria) this;
        }

        public Criteria andAddressIsNull() {
            addCriterion("address is null");
            return (Criteria) this;
        }

        public Criteria andAddressIsNotNull() {
            addCriterion("address is not null");
            return (Criteria) this;
        }

        public Criteria andAddressEqualTo(String value) {
            addCriterion("address =", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotEqualTo(String value) {
            addCriterion("address <>", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThan(String value) {
            addCriterion("address >", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThanOrEqualTo(String value) {
            addCriterion("address >=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThan(String value) {
            addCriterion("address <", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThanOrEqualTo(String value) {
            addCriterion("address <=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLike(String value) {
            addCriterion("address like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotLike(String value) {
            addCriterion("address not like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressIn(List<String> values) {
            addCriterion("address in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotIn(List<String> values) {
            addCriterion("address not in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressBetween(String value1, String value2) {
            addCriterion("address between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotBetween(String value1, String value2) {
            addCriterion("address not between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andCaseIdIsNull() {
            addCriterion("case_id is null");
            return (Criteria) this;
        }

        public Criteria andCaseIdIsNotNull() {
            addCriterion("case_id is not null");
            return (Criteria) this;
        }

        public Criteria andCaseIdEqualTo(String value) {
            addCriterion("case_id =", value, "caseId");
            return (Criteria) this;
        }

        public Criteria andCaseIdNotEqualTo(String value) {
            addCriterion("case_id <>", value, "caseId");
            return (Criteria) this;
        }

        public Criteria andCaseIdGreaterThan(String value) {
            addCriterion("case_id >", value, "caseId");
            return (Criteria) this;
        }

        public Criteria andCaseIdGreaterThanOrEqualTo(String value) {
            addCriterion("case_id >=", value, "caseId");
            return (Criteria) this;
        }

        public Criteria andCaseIdLessThan(String value) {
            addCriterion("case_id <", value, "caseId");
            return (Criteria) this;
        }

        public Criteria andCaseIdLessThanOrEqualTo(String value) {
            addCriterion("case_id <=", value, "caseId");
            return (Criteria) this;
        }

        public Criteria andCaseIdLike(String value) {
            addCriterion("case_id like", value, "caseId");
            return (Criteria) this;
        }

        public Criteria andCaseIdNotLike(String value) {
            addCriterion("case_id not like", value, "caseId");
            return (Criteria) this;
        }

        public Criteria andCaseIdIn(List<String> values) {
            addCriterion("case_id in", values, "caseId");
            return (Criteria) this;
        }

        public Criteria andCaseIdNotIn(List<String> values) {
            addCriterion("case_id not in", values, "caseId");
            return (Criteria) this;
        }

        public Criteria andCaseIdBetween(String value1, String value2) {
            addCriterion("case_id between", value1, value2, "caseId");
            return (Criteria) this;
        }

        public Criteria andCaseIdNotBetween(String value1, String value2) {
            addCriterion("case_id not between", value1, value2, "caseId");
            return (Criteria) this;
        }

        public Criteria andAdrCatIsNull() {
            addCriterion("adr_cat is null");
            return (Criteria) this;
        }

        public Criteria andAdrCatIsNotNull() {
            addCriterion("adr_cat is not null");
            return (Criteria) this;
        }

        public Criteria andAdrCatEqualTo(String value) {
            addCriterion("adr_cat =", value, "adrCat");
            return (Criteria) this;
        }

        public Criteria andAdrCatNotEqualTo(String value) {
            addCriterion("adr_cat <>", value, "adrCat");
            return (Criteria) this;
        }

        public Criteria andAdrCatGreaterThan(String value) {
            addCriterion("adr_cat >", value, "adrCat");
            return (Criteria) this;
        }

        public Criteria andAdrCatGreaterThanOrEqualTo(String value) {
            addCriterion("adr_cat >=", value, "adrCat");
            return (Criteria) this;
        }

        public Criteria andAdrCatLessThan(String value) {
            addCriterion("adr_cat <", value, "adrCat");
            return (Criteria) this;
        }

        public Criteria andAdrCatLessThanOrEqualTo(String value) {
            addCriterion("adr_cat <=", value, "adrCat");
            return (Criteria) this;
        }

        public Criteria andAdrCatLike(String value) {
            addCriterion("adr_cat like", value, "adrCat");
            return (Criteria) this;
        }

        public Criteria andAdrCatNotLike(String value) {
            addCriterion("adr_cat not like", value, "adrCat");
            return (Criteria) this;
        }

        public Criteria andAdrCatIn(List<String> values) {
            addCriterion("adr_cat in", values, "adrCat");
            return (Criteria) this;
        }

        public Criteria andAdrCatNotIn(List<String> values) {
            addCriterion("adr_cat not in", values, "adrCat");
            return (Criteria) this;
        }

        public Criteria andAdrCatBetween(String value1, String value2) {
            addCriterion("adr_cat between", value1, value2, "adrCat");
            return (Criteria) this;
        }

        public Criteria andAdrCatNotBetween(String value1, String value2) {
            addCriterion("adr_cat not between", value1, value2, "adrCat");
            return (Criteria) this;
        }

        public Criteria andCheckAppIsNull() {
            addCriterion("check_app is null");
            return (Criteria) this;
        }

        public Criteria andCheckAppIsNotNull() {
            addCriterion("check_app is not null");
            return (Criteria) this;
        }

        public Criteria andCheckAppEqualTo(Integer value) {
            addCriterion("check_app =", value, "checkApp");
            return (Criteria) this;
        }

        public Criteria andCheckAppNotEqualTo(Integer value) {
            addCriterion("check_app <>", value, "checkApp");
            return (Criteria) this;
        }

        public Criteria andCheckAppGreaterThan(Integer value) {
            addCriterion("check_app >", value, "checkApp");
            return (Criteria) this;
        }

        public Criteria andCheckAppGreaterThanOrEqualTo(Integer value) {
            addCriterion("check_app >=", value, "checkApp");
            return (Criteria) this;
        }

        public Criteria andCheckAppLessThan(Integer value) {
            addCriterion("check_app <", value, "checkApp");
            return (Criteria) this;
        }

        public Criteria andCheckAppLessThanOrEqualTo(Integer value) {
            addCriterion("check_app <=", value, "checkApp");
            return (Criteria) this;
        }

        public Criteria andCheckAppIn(List<Integer> values) {
            addCriterion("check_app in", values, "checkApp");
            return (Criteria) this;
        }

        public Criteria andCheckAppNotIn(List<Integer> values) {
            addCriterion("check_app not in", values, "checkApp");
            return (Criteria) this;
        }

        public Criteria andCheckAppBetween(Integer value1, Integer value2) {
            addCriterion("check_app between", value1, value2, "checkApp");
            return (Criteria) this;
        }

        public Criteria andCheckAppNotBetween(Integer value1, Integer value2) {
            addCriterion("check_app not between", value1, value2, "checkApp");
            return (Criteria) this;
        }

        public Criteria andMailAppIsNull() {
            addCriterion("mail_app is null");
            return (Criteria) this;
        }

        public Criteria andMailAppIsNotNull() {
            addCriterion("mail_app is not null");
            return (Criteria) this;
        }

        public Criteria andMailAppEqualTo(Integer value) {
            addCriterion("mail_app =", value, "mailApp");
            return (Criteria) this;
        }

        public Criteria andMailAppNotEqualTo(Integer value) {
            addCriterion("mail_app <>", value, "mailApp");
            return (Criteria) this;
        }

        public Criteria andMailAppGreaterThan(Integer value) {
            addCriterion("mail_app >", value, "mailApp");
            return (Criteria) this;
        }

        public Criteria andMailAppGreaterThanOrEqualTo(Integer value) {
            addCriterion("mail_app >=", value, "mailApp");
            return (Criteria) this;
        }

        public Criteria andMailAppLessThan(Integer value) {
            addCriterion("mail_app <", value, "mailApp");
            return (Criteria) this;
        }

        public Criteria andMailAppLessThanOrEqualTo(Integer value) {
            addCriterion("mail_app <=", value, "mailApp");
            return (Criteria) this;
        }

        public Criteria andMailAppIn(List<Integer> values) {
            addCriterion("mail_app in", values, "mailApp");
            return (Criteria) this;
        }

        public Criteria andMailAppNotIn(List<Integer> values) {
            addCriterion("mail_app not in", values, "mailApp");
            return (Criteria) this;
        }

        public Criteria andMailAppBetween(Integer value1, Integer value2) {
            addCriterion("mail_app between", value1, value2, "mailApp");
            return (Criteria) this;
        }

        public Criteria andMailAppNotBetween(Integer value1, Integer value2) {
            addCriterion("mail_app not between", value1, value2, "mailApp");
            return (Criteria) this;
        }

        public Criteria andVisAppIsNull() {
            addCriterion("vis_app is null");
            return (Criteria) this;
        }

        public Criteria andVisAppIsNotNull() {
            addCriterion("vis_app is not null");
            return (Criteria) this;
        }

        public Criteria andVisAppEqualTo(Integer value) {
            addCriterion("vis_app =", value, "visApp");
            return (Criteria) this;
        }

        public Criteria andVisAppNotEqualTo(Integer value) {
            addCriterion("vis_app <>", value, "visApp");
            return (Criteria) this;
        }

        public Criteria andVisAppGreaterThan(Integer value) {
            addCriterion("vis_app >", value, "visApp");
            return (Criteria) this;
        }

        public Criteria andVisAppGreaterThanOrEqualTo(Integer value) {
            addCriterion("vis_app >=", value, "visApp");
            return (Criteria) this;
        }

        public Criteria andVisAppLessThan(Integer value) {
            addCriterion("vis_app <", value, "visApp");
            return (Criteria) this;
        }

        public Criteria andVisAppLessThanOrEqualTo(Integer value) {
            addCriterion("vis_app <=", value, "visApp");
            return (Criteria) this;
        }

        public Criteria andVisAppIn(List<Integer> values) {
            addCriterion("vis_app in", values, "visApp");
            return (Criteria) this;
        }

        public Criteria andVisAppNotIn(List<Integer> values) {
            addCriterion("vis_app not in", values, "visApp");
            return (Criteria) this;
        }

        public Criteria andVisAppBetween(Integer value1, Integer value2) {
            addCriterion("vis_app between", value1, value2, "visApp");
            return (Criteria) this;
        }

        public Criteria andVisAppNotBetween(Integer value1, Integer value2) {
            addCriterion("vis_app not between", value1, value2, "visApp");
            return (Criteria) this;
        }

        public Criteria andRelationIsNull() {
            addCriterion("relation is null");
            return (Criteria) this;
        }

        public Criteria andRelationIsNotNull() {
            addCriterion("relation is not null");
            return (Criteria) this;
        }

        public Criteria andRelationEqualTo(String value) {
            addCriterion("relation =", value, "relation");
            return (Criteria) this;
        }

        public Criteria andRelationNotEqualTo(String value) {
            addCriterion("relation <>", value, "relation");
            return (Criteria) this;
        }

        public Criteria andRelationGreaterThan(String value) {
            addCriterion("relation >", value, "relation");
            return (Criteria) this;
        }

        public Criteria andRelationGreaterThanOrEqualTo(String value) {
            addCriterion("relation >=", value, "relation");
            return (Criteria) this;
        }

        public Criteria andRelationLessThan(String value) {
            addCriterion("relation <", value, "relation");
            return (Criteria) this;
        }

        public Criteria andRelationLessThanOrEqualTo(String value) {
            addCriterion("relation <=", value, "relation");
            return (Criteria) this;
        }

        public Criteria andRelationLike(String value) {
            addCriterion("relation like", value, "relation");
            return (Criteria) this;
        }

        public Criteria andRelationNotLike(String value) {
            addCriterion("relation not like", value, "relation");
            return (Criteria) this;
        }

        public Criteria andRelationIn(List<String> values) {
            addCriterion("relation in", values, "relation");
            return (Criteria) this;
        }

        public Criteria andRelationNotIn(List<String> values) {
            addCriterion("relation not in", values, "relation");
            return (Criteria) this;
        }

        public Criteria andRelationBetween(String value1, String value2) {
            addCriterion("relation between", value1, value2, "relation");
            return (Criteria) this;
        }

        public Criteria andRelationNotBetween(String value1, String value2) {
            addCriterion("relation not between", value1, value2, "relation");
            return (Criteria) this;
        }

        public Criteria andVisCountIsNull() {
            addCriterion("vis_count is null");
            return (Criteria) this;
        }

        public Criteria andVisCountIsNotNull() {
            addCriterion("vis_count is not null");
            return (Criteria) this;
        }

        public Criteria andVisCountEqualTo(Integer value) {
            addCriterion("vis_count =", value, "visCount");
            return (Criteria) this;
        }

        public Criteria andVisCountNotEqualTo(Integer value) {
            addCriterion("vis_count <>", value, "visCount");
            return (Criteria) this;
        }

        public Criteria andVisCountGreaterThan(Integer value) {
            addCriterion("vis_count >", value, "visCount");
            return (Criteria) this;
        }

        public Criteria andVisCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("vis_count >=", value, "visCount");
            return (Criteria) this;
        }

        public Criteria andVisCountLessThan(Integer value) {
            addCriterion("vis_count <", value, "visCount");
            return (Criteria) this;
        }

        public Criteria andVisCountLessThanOrEqualTo(Integer value) {
            addCriterion("vis_count <=", value, "visCount");
            return (Criteria) this;
        }

        public Criteria andVisCountIn(List<Integer> values) {
            addCriterion("vis_count in", values, "visCount");
            return (Criteria) this;
        }

        public Criteria andVisCountNotIn(List<Integer> values) {
            addCriterion("vis_count not in", values, "visCount");
            return (Criteria) this;
        }

        public Criteria andVisCountBetween(Integer value1, Integer value2) {
            addCriterion("vis_count between", value1, value2, "visCount");
            return (Criteria) this;
        }

        public Criteria andVisCountNotBetween(Integer value1, Integer value2) {
            addCriterion("vis_count not between", value1, value2, "visCount");
            return (Criteria) this;
        }

        public Criteria andMailCountIsNull() {
            addCriterion("mail_count is null");
            return (Criteria) this;
        }

        public Criteria andMailCountIsNotNull() {
            addCriterion("mail_count is not null");
            return (Criteria) this;
        }

        public Criteria andMailCountEqualTo(Integer value) {
            addCriterion("mail_count =", value, "mailCount");
            return (Criteria) this;
        }

        public Criteria andMailCountNotEqualTo(Integer value) {
            addCriterion("mail_count <>", value, "mailCount");
            return (Criteria) this;
        }

        public Criteria andMailCountGreaterThan(Integer value) {
            addCriterion("mail_count >", value, "mailCount");
            return (Criteria) this;
        }

        public Criteria andMailCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("mail_count >=", value, "mailCount");
            return (Criteria) this;
        }

        public Criteria andMailCountLessThan(Integer value) {
            addCriterion("mail_count <", value, "mailCount");
            return (Criteria) this;
        }

        public Criteria andMailCountLessThanOrEqualTo(Integer value) {
            addCriterion("mail_count <=", value, "mailCount");
            return (Criteria) this;
        }

        public Criteria andMailCountIn(List<Integer> values) {
            addCriterion("mail_count in", values, "mailCount");
            return (Criteria) this;
        }

        public Criteria andMailCountNotIn(List<Integer> values) {
            addCriterion("mail_count not in", values, "mailCount");
            return (Criteria) this;
        }

        public Criteria andMailCountBetween(Integer value1, Integer value2) {
            addCriterion("mail_count between", value1, value2, "mailCount");
            return (Criteria) this;
        }

        public Criteria andMailCountNotBetween(Integer value1, Integer value2) {
            addCriterion("mail_count not between", value1, value2, "mailCount");
            return (Criteria) this;
        }

        public Criteria andIsnewIsNull() {
            addCriterion("isnew is null");
            return (Criteria) this;
        }

        public Criteria andIsnewIsNotNull() {
            addCriterion("isnew is not null");
            return (Criteria) this;
        }

        public Criteria andIsnewEqualTo(Integer value) {
            addCriterion("isnew =", value, "isnew");
            return (Criteria) this;
        }

        public Criteria andIsnewNotEqualTo(Integer value) {
            addCriterion("isnew <>", value, "isnew");
            return (Criteria) this;
        }

        public Criteria andIsnewGreaterThan(Integer value) {
            addCriterion("isnew >", value, "isnew");
            return (Criteria) this;
        }

        public Criteria andIsnewGreaterThanOrEqualTo(Integer value) {
            addCriterion("isnew >=", value, "isnew");
            return (Criteria) this;
        }

        public Criteria andIsnewLessThan(Integer value) {
            addCriterion("isnew <", value, "isnew");
            return (Criteria) this;
        }

        public Criteria andIsnewLessThanOrEqualTo(Integer value) {
            addCriterion("isnew <=", value, "isnew");
            return (Criteria) this;
        }

        public Criteria andIsnewIn(List<Integer> values) {
            addCriterion("isnew in", values, "isnew");
            return (Criteria) this;
        }

        public Criteria andIsnewNotIn(List<Integer> values) {
            addCriterion("isnew not in", values, "isnew");
            return (Criteria) this;
        }

        public Criteria andIsnewBetween(Integer value1, Integer value2) {
            addCriterion("isnew between", value1, value2, "isnew");
            return (Criteria) this;
        }

        public Criteria andIsnewNotBetween(Integer value1, Integer value2) {
            addCriterion("isnew not between", value1, value2, "isnew");
            return (Criteria) this;
        }

        public Criteria andCreateEmpIdIsNull() {
            addCriterion("create_emp_id is null");
            return (Criteria) this;
        }

        public Criteria andCreateEmpIdIsNotNull() {
            addCriterion("create_emp_id is not null");
            return (Criteria) this;
        }

        public Criteria andCreateEmpIdEqualTo(String value) {
            addCriterion("create_emp_id =", value, "createEmpId");
            return (Criteria) this;
        }

        public Criteria andCreateEmpIdNotEqualTo(String value) {
            addCriterion("create_emp_id <>", value, "createEmpId");
            return (Criteria) this;
        }

        public Criteria andCreateEmpIdGreaterThan(String value) {
            addCriterion("create_emp_id >", value, "createEmpId");
            return (Criteria) this;
        }

        public Criteria andCreateEmpIdGreaterThanOrEqualTo(String value) {
            addCriterion("create_emp_id >=", value, "createEmpId");
            return (Criteria) this;
        }

        public Criteria andCreateEmpIdLessThan(String value) {
            addCriterion("create_emp_id <", value, "createEmpId");
            return (Criteria) this;
        }

        public Criteria andCreateEmpIdLessThanOrEqualTo(String value) {
            addCriterion("create_emp_id <=", value, "createEmpId");
            return (Criteria) this;
        }

        public Criteria andCreateEmpIdLike(String value) {
            addCriterion("create_emp_id like", value, "createEmpId");
            return (Criteria) this;
        }

        public Criteria andCreateEmpIdNotLike(String value) {
            addCriterion("create_emp_id not like", value, "createEmpId");
            return (Criteria) this;
        }

        public Criteria andCreateEmpIdIn(List<String> values) {
            addCriterion("create_emp_id in", values, "createEmpId");
            return (Criteria) this;
        }

        public Criteria andCreateEmpIdNotIn(List<String> values) {
            addCriterion("create_emp_id not in", values, "createEmpId");
            return (Criteria) this;
        }

        public Criteria andCreateEmpIdBetween(String value1, String value2) {
            addCriterion("create_emp_id between", value1, value2, "createEmpId");
            return (Criteria) this;
        }

        public Criteria andCreateEmpIdNotBetween(String value1, String value2) {
            addCriterion("create_emp_id not between", value1, value2, "createEmpId");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andSourceIsNull() {
            addCriterion("source is null");
            return (Criteria) this;
        }

        public Criteria andSourceIsNotNull() {
            addCriterion("source is not null");
            return (Criteria) this;
        }

        public Criteria andSourceEqualTo(String value) {
            addCriterion("source =", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceNotEqualTo(String value) {
            addCriterion("source <>", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceGreaterThan(String value) {
            addCriterion("source >", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceGreaterThanOrEqualTo(String value) {
            addCriterion("source >=", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceLessThan(String value) {
            addCriterion("source <", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceLessThanOrEqualTo(String value) {
            addCriterion("source <=", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceLike(String value) {
            addCriterion("source like", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceNotLike(String value) {
            addCriterion("source not like", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceIn(List<String> values) {
            addCriterion("source in", values, "source");
            return (Criteria) this;
        }

        public Criteria andSourceNotIn(List<String> values) {
            addCriterion("source not in", values, "source");
            return (Criteria) this;
        }

        public Criteria andSourceBetween(String value1, String value2) {
            addCriterion("source between", value1, value2, "source");
            return (Criteria) this;
        }

        public Criteria andSourceNotBetween(String value1, String value2) {
            addCriterion("source not between", value1, value2, "source");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table address
     *
     * @mbg.generated do_not_delete_during_merge Thu Oct 18 15:28:41 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table address
     *
     * @mbg.generated Thu Oct 18 15:28:41 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}