package com.atguigu.bean;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CaseApplyExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table case_apply
     *
     * @mbg.generated Thu Oct 18 15:28:41 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table case_apply
     *
     * @mbg.generated Thu Oct 18 15:28:41 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table case_apply
     *
     * @mbg.generated Thu Oct 18 15:28:41 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_apply
     *
     * @mbg.generated Thu Oct 18 15:28:41 CST 2018
     */
    public CaseApplyExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_apply
     *
     * @mbg.generated Thu Oct 18 15:28:41 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_apply
     *
     * @mbg.generated Thu Oct 18 15:28:41 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_apply
     *
     * @mbg.generated Thu Oct 18 15:28:41 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_apply
     *
     * @mbg.generated Thu Oct 18 15:28:41 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_apply
     *
     * @mbg.generated Thu Oct 18 15:28:41 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_apply
     *
     * @mbg.generated Thu Oct 18 15:28:41 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_apply
     *
     * @mbg.generated Thu Oct 18 15:28:41 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_apply
     *
     * @mbg.generated Thu Oct 18 15:28:41 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_apply
     *
     * @mbg.generated Thu Oct 18 15:28:41 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_apply
     *
     * @mbg.generated Thu Oct 18 15:28:41 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table case_apply
     *
     * @mbg.generated Thu Oct 18 15:28:41 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andStateIsNull() {
            addCriterion("state is null");
            return (Criteria) this;
        }

        public Criteria andStateIsNotNull() {
            addCriterion("state is not null");
            return (Criteria) this;
        }

        public Criteria andStateEqualTo(Integer value) {
            addCriterion("state =", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotEqualTo(Integer value) {
            addCriterion("state <>", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThan(Integer value) {
            addCriterion("state >", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThanOrEqualTo(Integer value) {
            addCriterion("state >=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThan(Integer value) {
            addCriterion("state <", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThanOrEqualTo(Integer value) {
            addCriterion("state <=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateIn(List<Integer> values) {
            addCriterion("state in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotIn(List<Integer> values) {
            addCriterion("state not in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateBetween(Integer value1, Integer value2) {
            addCriterion("state between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotBetween(Integer value1, Integer value2) {
            addCriterion("state not between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andApplyTypeIsNull() {
            addCriterion("apply_type is null");
            return (Criteria) this;
        }

        public Criteria andApplyTypeIsNotNull() {
            addCriterion("apply_type is not null");
            return (Criteria) this;
        }

        public Criteria andApplyTypeEqualTo(Integer value) {
            addCriterion("apply_type =", value, "applyType");
            return (Criteria) this;
        }

        public Criteria andApplyTypeNotEqualTo(Integer value) {
            addCriterion("apply_type <>", value, "applyType");
            return (Criteria) this;
        }

        public Criteria andApplyTypeGreaterThan(Integer value) {
            addCriterion("apply_type >", value, "applyType");
            return (Criteria) this;
        }

        public Criteria andApplyTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("apply_type >=", value, "applyType");
            return (Criteria) this;
        }

        public Criteria andApplyTypeLessThan(Integer value) {
            addCriterion("apply_type <", value, "applyType");
            return (Criteria) this;
        }

        public Criteria andApplyTypeLessThanOrEqualTo(Integer value) {
            addCriterion("apply_type <=", value, "applyType");
            return (Criteria) this;
        }

        public Criteria andApplyTypeIn(List<Integer> values) {
            addCriterion("apply_type in", values, "applyType");
            return (Criteria) this;
        }

        public Criteria andApplyTypeNotIn(List<Integer> values) {
            addCriterion("apply_type not in", values, "applyType");
            return (Criteria) this;
        }

        public Criteria andApplyTypeBetween(Integer value1, Integer value2) {
            addCriterion("apply_type between", value1, value2, "applyType");
            return (Criteria) this;
        }

        public Criteria andApplyTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("apply_type not between", value1, value2, "applyType");
            return (Criteria) this;
        }

        public Criteria andChCat1IsNull() {
            addCriterion("ch_cat_1 is null");
            return (Criteria) this;
        }

        public Criteria andChCat1IsNotNull() {
            addCriterion("ch_cat_1 is not null");
            return (Criteria) this;
        }

        public Criteria andChCat1EqualTo(String value) {
            addCriterion("ch_cat_1 =", value, "chCat1");
            return (Criteria) this;
        }

        public Criteria andChCat1NotEqualTo(String value) {
            addCriterion("ch_cat_1 <>", value, "chCat1");
            return (Criteria) this;
        }

        public Criteria andChCat1GreaterThan(String value) {
            addCriterion("ch_cat_1 >", value, "chCat1");
            return (Criteria) this;
        }

        public Criteria andChCat1GreaterThanOrEqualTo(String value) {
            addCriterion("ch_cat_1 >=", value, "chCat1");
            return (Criteria) this;
        }

        public Criteria andChCat1LessThan(String value) {
            addCriterion("ch_cat_1 <", value, "chCat1");
            return (Criteria) this;
        }

        public Criteria andChCat1LessThanOrEqualTo(String value) {
            addCriterion("ch_cat_1 <=", value, "chCat1");
            return (Criteria) this;
        }

        public Criteria andChCat1Like(String value) {
            addCriterion("ch_cat_1 like", value, "chCat1");
            return (Criteria) this;
        }

        public Criteria andChCat1NotLike(String value) {
            addCriterion("ch_cat_1 not like", value, "chCat1");
            return (Criteria) this;
        }

        public Criteria andChCat1In(List<String> values) {
            addCriterion("ch_cat_1 in", values, "chCat1");
            return (Criteria) this;
        }

        public Criteria andChCat1NotIn(List<String> values) {
            addCriterion("ch_cat_1 not in", values, "chCat1");
            return (Criteria) this;
        }

        public Criteria andChCat1Between(String value1, String value2) {
            addCriterion("ch_cat_1 between", value1, value2, "chCat1");
            return (Criteria) this;
        }

        public Criteria andChCat1NotBetween(String value1, String value2) {
            addCriterion("ch_cat_1 not between", value1, value2, "chCat1");
            return (Criteria) this;
        }

        public Criteria andChCat2IsNull() {
            addCriterion("ch_cat_2 is null");
            return (Criteria) this;
        }

        public Criteria andChCat2IsNotNull() {
            addCriterion("ch_cat_2 is not null");
            return (Criteria) this;
        }

        public Criteria andChCat2EqualTo(String value) {
            addCriterion("ch_cat_2 =", value, "chCat2");
            return (Criteria) this;
        }

        public Criteria andChCat2NotEqualTo(String value) {
            addCriterion("ch_cat_2 <>", value, "chCat2");
            return (Criteria) this;
        }

        public Criteria andChCat2GreaterThan(String value) {
            addCriterion("ch_cat_2 >", value, "chCat2");
            return (Criteria) this;
        }

        public Criteria andChCat2GreaterThanOrEqualTo(String value) {
            addCriterion("ch_cat_2 >=", value, "chCat2");
            return (Criteria) this;
        }

        public Criteria andChCat2LessThan(String value) {
            addCriterion("ch_cat_2 <", value, "chCat2");
            return (Criteria) this;
        }

        public Criteria andChCat2LessThanOrEqualTo(String value) {
            addCriterion("ch_cat_2 <=", value, "chCat2");
            return (Criteria) this;
        }

        public Criteria andChCat2Like(String value) {
            addCriterion("ch_cat_2 like", value, "chCat2");
            return (Criteria) this;
        }

        public Criteria andChCat2NotLike(String value) {
            addCriterion("ch_cat_2 not like", value, "chCat2");
            return (Criteria) this;
        }

        public Criteria andChCat2In(List<String> values) {
            addCriterion("ch_cat_2 in", values, "chCat2");
            return (Criteria) this;
        }

        public Criteria andChCat2NotIn(List<String> values) {
            addCriterion("ch_cat_2 not in", values, "chCat2");
            return (Criteria) this;
        }

        public Criteria andChCat2Between(String value1, String value2) {
            addCriterion("ch_cat_2 between", value1, value2, "chCat2");
            return (Criteria) this;
        }

        public Criteria andChCat2NotBetween(String value1, String value2) {
            addCriterion("ch_cat_2 not between", value1, value2, "chCat2");
            return (Criteria) this;
        }

        public Criteria andAddressIdIsNull() {
            addCriterion("address_id is null");
            return (Criteria) this;
        }

        public Criteria andAddressIdIsNotNull() {
            addCriterion("address_id is not null");
            return (Criteria) this;
        }

        public Criteria andAddressIdEqualTo(String value) {
            addCriterion("address_id =", value, "addressId");
            return (Criteria) this;
        }

        public Criteria andAddressIdNotEqualTo(String value) {
            addCriterion("address_id <>", value, "addressId");
            return (Criteria) this;
        }

        public Criteria andAddressIdGreaterThan(String value) {
            addCriterion("address_id >", value, "addressId");
            return (Criteria) this;
        }

        public Criteria andAddressIdGreaterThanOrEqualTo(String value) {
            addCriterion("address_id >=", value, "addressId");
            return (Criteria) this;
        }

        public Criteria andAddressIdLessThan(String value) {
            addCriterion("address_id <", value, "addressId");
            return (Criteria) this;
        }

        public Criteria andAddressIdLessThanOrEqualTo(String value) {
            addCriterion("address_id <=", value, "addressId");
            return (Criteria) this;
        }

        public Criteria andAddressIdLike(String value) {
            addCriterion("address_id like", value, "addressId");
            return (Criteria) this;
        }

        public Criteria andAddressIdNotLike(String value) {
            addCriterion("address_id not like", value, "addressId");
            return (Criteria) this;
        }

        public Criteria andAddressIdIn(List<String> values) {
            addCriterion("address_id in", values, "addressId");
            return (Criteria) this;
        }

        public Criteria andAddressIdNotIn(List<String> values) {
            addCriterion("address_id not in", values, "addressId");
            return (Criteria) this;
        }

        public Criteria andAddressIdBetween(String value1, String value2) {
            addCriterion("address_id between", value1, value2, "addressId");
            return (Criteria) this;
        }

        public Criteria andAddressIdNotBetween(String value1, String value2) {
            addCriterion("address_id not between", value1, value2, "addressId");
            return (Criteria) this;
        }

        public Criteria andMsgStateIsNull() {
            addCriterion("msg_state is null");
            return (Criteria) this;
        }

        public Criteria andMsgStateIsNotNull() {
            addCriterion("msg_state is not null");
            return (Criteria) this;
        }

        public Criteria andMsgStateEqualTo(Integer value) {
            addCriterion("msg_state =", value, "msgState");
            return (Criteria) this;
        }

        public Criteria andMsgStateNotEqualTo(Integer value) {
            addCriterion("msg_state <>", value, "msgState");
            return (Criteria) this;
        }

        public Criteria andMsgStateGreaterThan(Integer value) {
            addCriterion("msg_state >", value, "msgState");
            return (Criteria) this;
        }

        public Criteria andMsgStateGreaterThanOrEqualTo(Integer value) {
            addCriterion("msg_state >=", value, "msgState");
            return (Criteria) this;
        }

        public Criteria andMsgStateLessThan(Integer value) {
            addCriterion("msg_state <", value, "msgState");
            return (Criteria) this;
        }

        public Criteria andMsgStateLessThanOrEqualTo(Integer value) {
            addCriterion("msg_state <=", value, "msgState");
            return (Criteria) this;
        }

        public Criteria andMsgStateIn(List<Integer> values) {
            addCriterion("msg_state in", values, "msgState");
            return (Criteria) this;
        }

        public Criteria andMsgStateNotIn(List<Integer> values) {
            addCriterion("msg_state not in", values, "msgState");
            return (Criteria) this;
        }

        public Criteria andMsgStateBetween(Integer value1, Integer value2) {
            addCriterion("msg_state between", value1, value2, "msgState");
            return (Criteria) this;
        }

        public Criteria andMsgStateNotBetween(Integer value1, Integer value2) {
            addCriterion("msg_state not between", value1, value2, "msgState");
            return (Criteria) this;
        }

        public Criteria andCaseIdIsNull() {
            addCriterion("case_id is null");
            return (Criteria) this;
        }

        public Criteria andCaseIdIsNotNull() {
            addCriterion("case_id is not null");
            return (Criteria) this;
        }

        public Criteria andCaseIdEqualTo(String value) {
            addCriterion("case_id =", value, "caseId");
            return (Criteria) this;
        }

        public Criteria andCaseIdNotEqualTo(String value) {
            addCriterion("case_id <>", value, "caseId");
            return (Criteria) this;
        }

        public Criteria andCaseIdGreaterThan(String value) {
            addCriterion("case_id >", value, "caseId");
            return (Criteria) this;
        }

        public Criteria andCaseIdGreaterThanOrEqualTo(String value) {
            addCriterion("case_id >=", value, "caseId");
            return (Criteria) this;
        }

        public Criteria andCaseIdLessThan(String value) {
            addCriterion("case_id <", value, "caseId");
            return (Criteria) this;
        }

        public Criteria andCaseIdLessThanOrEqualTo(String value) {
            addCriterion("case_id <=", value, "caseId");
            return (Criteria) this;
        }

        public Criteria andCaseIdLike(String value) {
            addCriterion("case_id like", value, "caseId");
            return (Criteria) this;
        }

        public Criteria andCaseIdNotLike(String value) {
            addCriterion("case_id not like", value, "caseId");
            return (Criteria) this;
        }

        public Criteria andCaseIdIn(List<String> values) {
            addCriterion("case_id in", values, "caseId");
            return (Criteria) this;
        }

        public Criteria andCaseIdNotIn(List<String> values) {
            addCriterion("case_id not in", values, "caseId");
            return (Criteria) this;
        }

        public Criteria andCaseIdBetween(String value1, String value2) {
            addCriterion("case_id between", value1, value2, "caseId");
            return (Criteria) this;
        }

        public Criteria andCaseIdNotBetween(String value1, String value2) {
            addCriterion("case_id not between", value1, value2, "caseId");
            return (Criteria) this;
        }

        public Criteria andApplyUserIsNull() {
            addCriterion("apply_user is null");
            return (Criteria) this;
        }

        public Criteria andApplyUserIsNotNull() {
            addCriterion("apply_user is not null");
            return (Criteria) this;
        }

        public Criteria andApplyUserEqualTo(String value) {
            addCriterion("apply_user =", value, "applyUser");
            return (Criteria) this;
        }

        public Criteria andApplyUserNotEqualTo(String value) {
            addCriterion("apply_user <>", value, "applyUser");
            return (Criteria) this;
        }

        public Criteria andApplyUserGreaterThan(String value) {
            addCriterion("apply_user >", value, "applyUser");
            return (Criteria) this;
        }

        public Criteria andApplyUserGreaterThanOrEqualTo(String value) {
            addCriterion("apply_user >=", value, "applyUser");
            return (Criteria) this;
        }

        public Criteria andApplyUserLessThan(String value) {
            addCriterion("apply_user <", value, "applyUser");
            return (Criteria) this;
        }

        public Criteria andApplyUserLessThanOrEqualTo(String value) {
            addCriterion("apply_user <=", value, "applyUser");
            return (Criteria) this;
        }

        public Criteria andApplyUserLike(String value) {
            addCriterion("apply_user like", value, "applyUser");
            return (Criteria) this;
        }

        public Criteria andApplyUserNotLike(String value) {
            addCriterion("apply_user not like", value, "applyUser");
            return (Criteria) this;
        }

        public Criteria andApplyUserIn(List<String> values) {
            addCriterion("apply_user in", values, "applyUser");
            return (Criteria) this;
        }

        public Criteria andApplyUserNotIn(List<String> values) {
            addCriterion("apply_user not in", values, "applyUser");
            return (Criteria) this;
        }

        public Criteria andApplyUserBetween(String value1, String value2) {
            addCriterion("apply_user between", value1, value2, "applyUser");
            return (Criteria) this;
        }

        public Criteria andApplyUserNotBetween(String value1, String value2) {
            addCriterion("apply_user not between", value1, value2, "applyUser");
            return (Criteria) this;
        }

        public Criteria andApplyUserNameIsNull() {
            addCriterion("apply_user_name is null");
            return (Criteria) this;
        }

        public Criteria andApplyUserNameIsNotNull() {
            addCriterion("apply_user_name is not null");
            return (Criteria) this;
        }

        public Criteria andApplyUserNameEqualTo(String value) {
            addCriterion("apply_user_name =", value, "applyUserName");
            return (Criteria) this;
        }

        public Criteria andApplyUserNameNotEqualTo(String value) {
            addCriterion("apply_user_name <>", value, "applyUserName");
            return (Criteria) this;
        }

        public Criteria andApplyUserNameGreaterThan(String value) {
            addCriterion("apply_user_name >", value, "applyUserName");
            return (Criteria) this;
        }

        public Criteria andApplyUserNameGreaterThanOrEqualTo(String value) {
            addCriterion("apply_user_name >=", value, "applyUserName");
            return (Criteria) this;
        }

        public Criteria andApplyUserNameLessThan(String value) {
            addCriterion("apply_user_name <", value, "applyUserName");
            return (Criteria) this;
        }

        public Criteria andApplyUserNameLessThanOrEqualTo(String value) {
            addCriterion("apply_user_name <=", value, "applyUserName");
            return (Criteria) this;
        }

        public Criteria andApplyUserNameLike(String value) {
            addCriterion("apply_user_name like", value, "applyUserName");
            return (Criteria) this;
        }

        public Criteria andApplyUserNameNotLike(String value) {
            addCriterion("apply_user_name not like", value, "applyUserName");
            return (Criteria) this;
        }

        public Criteria andApplyUserNameIn(List<String> values) {
            addCriterion("apply_user_name in", values, "applyUserName");
            return (Criteria) this;
        }

        public Criteria andApplyUserNameNotIn(List<String> values) {
            addCriterion("apply_user_name not in", values, "applyUserName");
            return (Criteria) this;
        }

        public Criteria andApplyUserNameBetween(String value1, String value2) {
            addCriterion("apply_user_name between", value1, value2, "applyUserName");
            return (Criteria) this;
        }

        public Criteria andApplyUserNameNotBetween(String value1, String value2) {
            addCriterion("apply_user_name not between", value1, value2, "applyUserName");
            return (Criteria) this;
        }

        public Criteria andSurUserIsNull() {
            addCriterion("sur_user is null");
            return (Criteria) this;
        }

        public Criteria andSurUserIsNotNull() {
            addCriterion("sur_user is not null");
            return (Criteria) this;
        }

        public Criteria andSurUserEqualTo(String value) {
            addCriterion("sur_user =", value, "surUser");
            return (Criteria) this;
        }

        public Criteria andSurUserNotEqualTo(String value) {
            addCriterion("sur_user <>", value, "surUser");
            return (Criteria) this;
        }

        public Criteria andSurUserGreaterThan(String value) {
            addCriterion("sur_user >", value, "surUser");
            return (Criteria) this;
        }

        public Criteria andSurUserGreaterThanOrEqualTo(String value) {
            addCriterion("sur_user >=", value, "surUser");
            return (Criteria) this;
        }

        public Criteria andSurUserLessThan(String value) {
            addCriterion("sur_user <", value, "surUser");
            return (Criteria) this;
        }

        public Criteria andSurUserLessThanOrEqualTo(String value) {
            addCriterion("sur_user <=", value, "surUser");
            return (Criteria) this;
        }

        public Criteria andSurUserLike(String value) {
            addCriterion("sur_user like", value, "surUser");
            return (Criteria) this;
        }

        public Criteria andSurUserNotLike(String value) {
            addCriterion("sur_user not like", value, "surUser");
            return (Criteria) this;
        }

        public Criteria andSurUserIn(List<String> values) {
            addCriterion("sur_user in", values, "surUser");
            return (Criteria) this;
        }

        public Criteria andSurUserNotIn(List<String> values) {
            addCriterion("sur_user not in", values, "surUser");
            return (Criteria) this;
        }

        public Criteria andSurUserBetween(String value1, String value2) {
            addCriterion("sur_user between", value1, value2, "surUser");
            return (Criteria) this;
        }

        public Criteria andSurUserNotBetween(String value1, String value2) {
            addCriterion("sur_user not between", value1, value2, "surUser");
            return (Criteria) this;
        }

        public Criteria andSurUserNameIsNull() {
            addCriterion("sur_user_name is null");
            return (Criteria) this;
        }

        public Criteria andSurUserNameIsNotNull() {
            addCriterion("sur_user_name is not null");
            return (Criteria) this;
        }

        public Criteria andSurUserNameEqualTo(String value) {
            addCriterion("sur_user_name =", value, "surUserName");
            return (Criteria) this;
        }

        public Criteria andSurUserNameNotEqualTo(String value) {
            addCriterion("sur_user_name <>", value, "surUserName");
            return (Criteria) this;
        }

        public Criteria andSurUserNameGreaterThan(String value) {
            addCriterion("sur_user_name >", value, "surUserName");
            return (Criteria) this;
        }

        public Criteria andSurUserNameGreaterThanOrEqualTo(String value) {
            addCriterion("sur_user_name >=", value, "surUserName");
            return (Criteria) this;
        }

        public Criteria andSurUserNameLessThan(String value) {
            addCriterion("sur_user_name <", value, "surUserName");
            return (Criteria) this;
        }

        public Criteria andSurUserNameLessThanOrEqualTo(String value) {
            addCriterion("sur_user_name <=", value, "surUserName");
            return (Criteria) this;
        }

        public Criteria andSurUserNameLike(String value) {
            addCriterion("sur_user_name like", value, "surUserName");
            return (Criteria) this;
        }

        public Criteria andSurUserNameNotLike(String value) {
            addCriterion("sur_user_name not like", value, "surUserName");
            return (Criteria) this;
        }

        public Criteria andSurUserNameIn(List<String> values) {
            addCriterion("sur_user_name in", values, "surUserName");
            return (Criteria) this;
        }

        public Criteria andSurUserNameNotIn(List<String> values) {
            addCriterion("sur_user_name not in", values, "surUserName");
            return (Criteria) this;
        }

        public Criteria andSurUserNameBetween(String value1, String value2) {
            addCriterion("sur_user_name between", value1, value2, "surUserName");
            return (Criteria) this;
        }

        public Criteria andSurUserNameNotBetween(String value1, String value2) {
            addCriterion("sur_user_name not between", value1, value2, "surUserName");
            return (Criteria) this;
        }

        public Criteria andAppTimeIsNull() {
            addCriterion("app_time is null");
            return (Criteria) this;
        }

        public Criteria andAppTimeIsNotNull() {
            addCriterion("app_time is not null");
            return (Criteria) this;
        }

        public Criteria andAppTimeEqualTo(Date value) {
            addCriterion("app_time =", value, "appTime");
            return (Criteria) this;
        }

        public Criteria andAppTimeNotEqualTo(Date value) {
            addCriterion("app_time <>", value, "appTime");
            return (Criteria) this;
        }

        public Criteria andAppTimeGreaterThan(Date value) {
            addCriterion("app_time >", value, "appTime");
            return (Criteria) this;
        }

        public Criteria andAppTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("app_time >=", value, "appTime");
            return (Criteria) this;
        }

        public Criteria andAppTimeLessThan(Date value) {
            addCriterion("app_time <", value, "appTime");
            return (Criteria) this;
        }

        public Criteria andAppTimeLessThanOrEqualTo(Date value) {
            addCriterion("app_time <=", value, "appTime");
            return (Criteria) this;
        }

        public Criteria andAppTimeIn(List<Date> values) {
            addCriterion("app_time in", values, "appTime");
            return (Criteria) this;
        }

        public Criteria andAppTimeNotIn(List<Date> values) {
            addCriterion("app_time not in", values, "appTime");
            return (Criteria) this;
        }

        public Criteria andAppTimeBetween(Date value1, Date value2) {
            addCriterion("app_time between", value1, value2, "appTime");
            return (Criteria) this;
        }

        public Criteria andAppTimeNotBetween(Date value1, Date value2) {
            addCriterion("app_time not between", value1, value2, "appTime");
            return (Criteria) this;
        }

        public Criteria andSurTimeIsNull() {
            addCriterion("sur_time is null");
            return (Criteria) this;
        }

        public Criteria andSurTimeIsNotNull() {
            addCriterion("sur_time is not null");
            return (Criteria) this;
        }

        public Criteria andSurTimeEqualTo(Date value) {
            addCriterion("sur_time =", value, "surTime");
            return (Criteria) this;
        }

        public Criteria andSurTimeNotEqualTo(Date value) {
            addCriterion("sur_time <>", value, "surTime");
            return (Criteria) this;
        }

        public Criteria andSurTimeGreaterThan(Date value) {
            addCriterion("sur_time >", value, "surTime");
            return (Criteria) this;
        }

        public Criteria andSurTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("sur_time >=", value, "surTime");
            return (Criteria) this;
        }

        public Criteria andSurTimeLessThan(Date value) {
            addCriterion("sur_time <", value, "surTime");
            return (Criteria) this;
        }

        public Criteria andSurTimeLessThanOrEqualTo(Date value) {
            addCriterion("sur_time <=", value, "surTime");
            return (Criteria) this;
        }

        public Criteria andSurTimeIn(List<Date> values) {
            addCriterion("sur_time in", values, "surTime");
            return (Criteria) this;
        }

        public Criteria andSurTimeNotIn(List<Date> values) {
            addCriterion("sur_time not in", values, "surTime");
            return (Criteria) this;
        }

        public Criteria andSurTimeBetween(Date value1, Date value2) {
            addCriterion("sur_time between", value1, value2, "surTime");
            return (Criteria) this;
        }

        public Criteria andSurTimeNotBetween(Date value1, Date value2) {
            addCriterion("sur_time not between", value1, value2, "surTime");
            return (Criteria) this;
        }

        public Criteria andContactUserIsNull() {
            addCriterion("contact_user is null");
            return (Criteria) this;
        }

        public Criteria andContactUserIsNotNull() {
            addCriterion("contact_user is not null");
            return (Criteria) this;
        }

        public Criteria andContactUserEqualTo(String value) {
            addCriterion("contact_user =", value, "contactUser");
            return (Criteria) this;
        }

        public Criteria andContactUserNotEqualTo(String value) {
            addCriterion("contact_user <>", value, "contactUser");
            return (Criteria) this;
        }

        public Criteria andContactUserGreaterThan(String value) {
            addCriterion("contact_user >", value, "contactUser");
            return (Criteria) this;
        }

        public Criteria andContactUserGreaterThanOrEqualTo(String value) {
            addCriterion("contact_user >=", value, "contactUser");
            return (Criteria) this;
        }

        public Criteria andContactUserLessThan(String value) {
            addCriterion("contact_user <", value, "contactUser");
            return (Criteria) this;
        }

        public Criteria andContactUserLessThanOrEqualTo(String value) {
            addCriterion("contact_user <=", value, "contactUser");
            return (Criteria) this;
        }

        public Criteria andContactUserLike(String value) {
            addCriterion("contact_user like", value, "contactUser");
            return (Criteria) this;
        }

        public Criteria andContactUserNotLike(String value) {
            addCriterion("contact_user not like", value, "contactUser");
            return (Criteria) this;
        }

        public Criteria andContactUserIn(List<String> values) {
            addCriterion("contact_user in", values, "contactUser");
            return (Criteria) this;
        }

        public Criteria andContactUserNotIn(List<String> values) {
            addCriterion("contact_user not in", values, "contactUser");
            return (Criteria) this;
        }

        public Criteria andContactUserBetween(String value1, String value2) {
            addCriterion("contact_user between", value1, value2, "contactUser");
            return (Criteria) this;
        }

        public Criteria andContactUserNotBetween(String value1, String value2) {
            addCriterion("contact_user not between", value1, value2, "contactUser");
            return (Criteria) this;
        }

        public Criteria andAddressIsNull() {
            addCriterion("address is null");
            return (Criteria) this;
        }

        public Criteria andAddressIsNotNull() {
            addCriterion("address is not null");
            return (Criteria) this;
        }

        public Criteria andAddressEqualTo(String value) {
            addCriterion("address =", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotEqualTo(String value) {
            addCriterion("address <>", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThan(String value) {
            addCriterion("address >", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThanOrEqualTo(String value) {
            addCriterion("address >=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThan(String value) {
            addCriterion("address <", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThanOrEqualTo(String value) {
            addCriterion("address <=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLike(String value) {
            addCriterion("address like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotLike(String value) {
            addCriterion("address not like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressIn(List<String> values) {
            addCriterion("address in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotIn(List<String> values) {
            addCriterion("address not in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressBetween(String value1, String value2) {
            addCriterion("address between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotBetween(String value1, String value2) {
            addCriterion("address not between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andChCountIsNull() {
            addCriterion("ch_count is null");
            return (Criteria) this;
        }

        public Criteria andChCountIsNotNull() {
            addCriterion("ch_count is not null");
            return (Criteria) this;
        }

        public Criteria andChCountEqualTo(Integer value) {
            addCriterion("ch_count =", value, "chCount");
            return (Criteria) this;
        }

        public Criteria andChCountNotEqualTo(Integer value) {
            addCriterion("ch_count <>", value, "chCount");
            return (Criteria) this;
        }

        public Criteria andChCountGreaterThan(Integer value) {
            addCriterion("ch_count >", value, "chCount");
            return (Criteria) this;
        }

        public Criteria andChCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("ch_count >=", value, "chCount");
            return (Criteria) this;
        }

        public Criteria andChCountLessThan(Integer value) {
            addCriterion("ch_count <", value, "chCount");
            return (Criteria) this;
        }

        public Criteria andChCountLessThanOrEqualTo(Integer value) {
            addCriterion("ch_count <=", value, "chCount");
            return (Criteria) this;
        }

        public Criteria andChCountIn(List<Integer> values) {
            addCriterion("ch_count in", values, "chCount");
            return (Criteria) this;
        }

        public Criteria andChCountNotIn(List<Integer> values) {
            addCriterion("ch_count not in", values, "chCount");
            return (Criteria) this;
        }

        public Criteria andChCountBetween(Integer value1, Integer value2) {
            addCriterion("ch_count between", value1, value2, "chCount");
            return (Criteria) this;
        }

        public Criteria andChCountNotBetween(Integer value1, Integer value2) {
            addCriterion("ch_count not between", value1, value2, "chCount");
            return (Criteria) this;
        }

        public Criteria andApprovalOpinionIsNull() {
            addCriterion("approval_opinion is null");
            return (Criteria) this;
        }

        public Criteria andApprovalOpinionIsNotNull() {
            addCriterion("approval_opinion is not null");
            return (Criteria) this;
        }

        public Criteria andApprovalOpinionEqualTo(String value) {
            addCriterion("approval_opinion =", value, "approvalOpinion");
            return (Criteria) this;
        }

        public Criteria andApprovalOpinionNotEqualTo(String value) {
            addCriterion("approval_opinion <>", value, "approvalOpinion");
            return (Criteria) this;
        }

        public Criteria andApprovalOpinionGreaterThan(String value) {
            addCriterion("approval_opinion >", value, "approvalOpinion");
            return (Criteria) this;
        }

        public Criteria andApprovalOpinionGreaterThanOrEqualTo(String value) {
            addCriterion("approval_opinion >=", value, "approvalOpinion");
            return (Criteria) this;
        }

        public Criteria andApprovalOpinionLessThan(String value) {
            addCriterion("approval_opinion <", value, "approvalOpinion");
            return (Criteria) this;
        }

        public Criteria andApprovalOpinionLessThanOrEqualTo(String value) {
            addCriterion("approval_opinion <=", value, "approvalOpinion");
            return (Criteria) this;
        }

        public Criteria andApprovalOpinionLike(String value) {
            addCriterion("approval_opinion like", value, "approvalOpinion");
            return (Criteria) this;
        }

        public Criteria andApprovalOpinionNotLike(String value) {
            addCriterion("approval_opinion not like", value, "approvalOpinion");
            return (Criteria) this;
        }

        public Criteria andApprovalOpinionIn(List<String> values) {
            addCriterion("approval_opinion in", values, "approvalOpinion");
            return (Criteria) this;
        }

        public Criteria andApprovalOpinionNotIn(List<String> values) {
            addCriterion("approval_opinion not in", values, "approvalOpinion");
            return (Criteria) this;
        }

        public Criteria andApprovalOpinionBetween(String value1, String value2) {
            addCriterion("approval_opinion between", value1, value2, "approvalOpinion");
            return (Criteria) this;
        }

        public Criteria andApprovalOpinionNotBetween(String value1, String value2) {
            addCriterion("approval_opinion not between", value1, value2, "approvalOpinion");
            return (Criteria) this;
        }

        public Criteria andMailTimeIsNull() {
            addCriterion("mail_time is null");
            return (Criteria) this;
        }

        public Criteria andMailTimeIsNotNull() {
            addCriterion("mail_time is not null");
            return (Criteria) this;
        }

        public Criteria andMailTimeEqualTo(Date value) {
            addCriterion("mail_time =", value, "mailTime");
            return (Criteria) this;
        }

        public Criteria andMailTimeNotEqualTo(Date value) {
            addCriterion("mail_time <>", value, "mailTime");
            return (Criteria) this;
        }

        public Criteria andMailTimeGreaterThan(Date value) {
            addCriterion("mail_time >", value, "mailTime");
            return (Criteria) this;
        }

        public Criteria andMailTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("mail_time >=", value, "mailTime");
            return (Criteria) this;
        }

        public Criteria andMailTimeLessThan(Date value) {
            addCriterion("mail_time <", value, "mailTime");
            return (Criteria) this;
        }

        public Criteria andMailTimeLessThanOrEqualTo(Date value) {
            addCriterion("mail_time <=", value, "mailTime");
            return (Criteria) this;
        }

        public Criteria andMailTimeIn(List<Date> values) {
            addCriterion("mail_time in", values, "mailTime");
            return (Criteria) this;
        }

        public Criteria andMailTimeNotIn(List<Date> values) {
            addCriterion("mail_time not in", values, "mailTime");
            return (Criteria) this;
        }

        public Criteria andMailTimeBetween(Date value1, Date value2) {
            addCriterion("mail_time between", value1, value2, "mailTime");
            return (Criteria) this;
        }

        public Criteria andMailTimeNotBetween(Date value1, Date value2) {
            addCriterion("mail_time not between", value1, value2, "mailTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table case_apply
     *
     * @mbg.generated do_not_delete_during_merge Thu Oct 18 15:28:41 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table case_apply
     *
     * @mbg.generated Thu Oct 18 15:28:41 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}