package com.atguigu.bean;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CasePaidExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table case_paid
     *
     * @mbg.generated Thu Oct 18 15:28:41 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table case_paid
     *
     * @mbg.generated Thu Oct 18 15:28:41 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table case_paid
     *
     * @mbg.generated Thu Oct 18 15:28:41 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_paid
     *
     * @mbg.generated Thu Oct 18 15:28:41 CST 2018
     */
    public CasePaidExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_paid
     *
     * @mbg.generated Thu Oct 18 15:28:41 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_paid
     *
     * @mbg.generated Thu Oct 18 15:28:41 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_paid
     *
     * @mbg.generated Thu Oct 18 15:28:41 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_paid
     *
     * @mbg.generated Thu Oct 18 15:28:41 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_paid
     *
     * @mbg.generated Thu Oct 18 15:28:41 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_paid
     *
     * @mbg.generated Thu Oct 18 15:28:41 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_paid
     *
     * @mbg.generated Thu Oct 18 15:28:41 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_paid
     *
     * @mbg.generated Thu Oct 18 15:28:41 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_paid
     *
     * @mbg.generated Thu Oct 18 15:28:41 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_paid
     *
     * @mbg.generated Thu Oct 18 15:28:41 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table case_paid
     *
     * @mbg.generated Thu Oct 18 15:28:41 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andStateIsNull() {
            addCriterion("state is null");
            return (Criteria) this;
        }

        public Criteria andStateIsNotNull() {
            addCriterion("state is not null");
            return (Criteria) this;
        }

        public Criteria andStateEqualTo(Integer value) {
            addCriterion("state =", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotEqualTo(Integer value) {
            addCriterion("state <>", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThan(Integer value) {
            addCriterion("state >", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThanOrEqualTo(Integer value) {
            addCriterion("state >=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThan(Integer value) {
            addCriterion("state <", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThanOrEqualTo(Integer value) {
            addCriterion("state <=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateIn(List<Integer> values) {
            addCriterion("state in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotIn(List<Integer> values) {
            addCriterion("state not in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateBetween(Integer value1, Integer value2) {
            addCriterion("state between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotBetween(Integer value1, Integer value2) {
            addCriterion("state not between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andCaseIdIsNull() {
            addCriterion("case_id is null");
            return (Criteria) this;
        }

        public Criteria andCaseIdIsNotNull() {
            addCriterion("case_id is not null");
            return (Criteria) this;
        }

        public Criteria andCaseIdEqualTo(String value) {
            addCriterion("case_id =", value, "caseId");
            return (Criteria) this;
        }

        public Criteria andCaseIdNotEqualTo(String value) {
            addCriterion("case_id <>", value, "caseId");
            return (Criteria) this;
        }

        public Criteria andCaseIdGreaterThan(String value) {
            addCriterion("case_id >", value, "caseId");
            return (Criteria) this;
        }

        public Criteria andCaseIdGreaterThanOrEqualTo(String value) {
            addCriterion("case_id >=", value, "caseId");
            return (Criteria) this;
        }

        public Criteria andCaseIdLessThan(String value) {
            addCriterion("case_id <", value, "caseId");
            return (Criteria) this;
        }

        public Criteria andCaseIdLessThanOrEqualTo(String value) {
            addCriterion("case_id <=", value, "caseId");
            return (Criteria) this;
        }

        public Criteria andCaseIdLike(String value) {
            addCriterion("case_id like", value, "caseId");
            return (Criteria) this;
        }

        public Criteria andCaseIdNotLike(String value) {
            addCriterion("case_id not like", value, "caseId");
            return (Criteria) this;
        }

        public Criteria andCaseIdIn(List<String> values) {
            addCriterion("case_id in", values, "caseId");
            return (Criteria) this;
        }

        public Criteria andCaseIdNotIn(List<String> values) {
            addCriterion("case_id not in", values, "caseId");
            return (Criteria) this;
        }

        public Criteria andCaseIdBetween(String value1, String value2) {
            addCriterion("case_id between", value1, value2, "caseId");
            return (Criteria) this;
        }

        public Criteria andCaseIdNotBetween(String value1, String value2) {
            addCriterion("case_id not between", value1, value2, "caseId");
            return (Criteria) this;
        }

        public Criteria andPtpTimeIsNull() {
            addCriterion("ptp_time is null");
            return (Criteria) this;
        }

        public Criteria andPtpTimeIsNotNull() {
            addCriterion("ptp_time is not null");
            return (Criteria) this;
        }

        public Criteria andPtpTimeEqualTo(Date value) {
            addCriterion("ptp_time =", value, "ptpTime");
            return (Criteria) this;
        }

        public Criteria andPtpTimeNotEqualTo(Date value) {
            addCriterion("ptp_time <>", value, "ptpTime");
            return (Criteria) this;
        }

        public Criteria andPtpTimeGreaterThan(Date value) {
            addCriterion("ptp_time >", value, "ptpTime");
            return (Criteria) this;
        }

        public Criteria andPtpTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("ptp_time >=", value, "ptpTime");
            return (Criteria) this;
        }

        public Criteria andPtpTimeLessThan(Date value) {
            addCriterion("ptp_time <", value, "ptpTime");
            return (Criteria) this;
        }

        public Criteria andPtpTimeLessThanOrEqualTo(Date value) {
            addCriterion("ptp_time <=", value, "ptpTime");
            return (Criteria) this;
        }

        public Criteria andPtpTimeIn(List<Date> values) {
            addCriterion("ptp_time in", values, "ptpTime");
            return (Criteria) this;
        }

        public Criteria andPtpTimeNotIn(List<Date> values) {
            addCriterion("ptp_time not in", values, "ptpTime");
            return (Criteria) this;
        }

        public Criteria andPtpTimeBetween(Date value1, Date value2) {
            addCriterion("ptp_time between", value1, value2, "ptpTime");
            return (Criteria) this;
        }

        public Criteria andPtpTimeNotBetween(Date value1, Date value2) {
            addCriterion("ptp_time not between", value1, value2, "ptpTime");
            return (Criteria) this;
        }

        public Criteria andPtpMoneyIsNull() {
            addCriterion("ptp_money is null");
            return (Criteria) this;
        }

        public Criteria andPtpMoneyIsNotNull() {
            addCriterion("ptp_money is not null");
            return (Criteria) this;
        }

        public Criteria andPtpMoneyEqualTo(BigDecimal value) {
            addCriterion("ptp_money =", value, "ptpMoney");
            return (Criteria) this;
        }

        public Criteria andPtpMoneyNotEqualTo(BigDecimal value) {
            addCriterion("ptp_money <>", value, "ptpMoney");
            return (Criteria) this;
        }

        public Criteria andPtpMoneyGreaterThan(BigDecimal value) {
            addCriterion("ptp_money >", value, "ptpMoney");
            return (Criteria) this;
        }

        public Criteria andPtpMoneyGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("ptp_money >=", value, "ptpMoney");
            return (Criteria) this;
        }

        public Criteria andPtpMoneyLessThan(BigDecimal value) {
            addCriterion("ptp_money <", value, "ptpMoney");
            return (Criteria) this;
        }

        public Criteria andPtpMoneyLessThanOrEqualTo(BigDecimal value) {
            addCriterion("ptp_money <=", value, "ptpMoney");
            return (Criteria) this;
        }

        public Criteria andPtpMoneyIn(List<BigDecimal> values) {
            addCriterion("ptp_money in", values, "ptpMoney");
            return (Criteria) this;
        }

        public Criteria andPtpMoneyNotIn(List<BigDecimal> values) {
            addCriterion("ptp_money not in", values, "ptpMoney");
            return (Criteria) this;
        }

        public Criteria andPtpMoneyBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ptp_money between", value1, value2, "ptpMoney");
            return (Criteria) this;
        }

        public Criteria andPtpMoneyNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ptp_money not between", value1, value2, "ptpMoney");
            return (Criteria) this;
        }

        public Criteria andCpTimeIsNull() {
            addCriterion("cp_time is null");
            return (Criteria) this;
        }

        public Criteria andCpTimeIsNotNull() {
            addCriterion("cp_time is not null");
            return (Criteria) this;
        }

        public Criteria andCpTimeEqualTo(Date value) {
            addCriterion("cp_time =", value, "cpTime");
            return (Criteria) this;
        }

        public Criteria andCpTimeNotEqualTo(Date value) {
            addCriterion("cp_time <>", value, "cpTime");
            return (Criteria) this;
        }

        public Criteria andCpTimeGreaterThan(Date value) {
            addCriterion("cp_time >", value, "cpTime");
            return (Criteria) this;
        }

        public Criteria andCpTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("cp_time >=", value, "cpTime");
            return (Criteria) this;
        }

        public Criteria andCpTimeLessThan(Date value) {
            addCriterion("cp_time <", value, "cpTime");
            return (Criteria) this;
        }

        public Criteria andCpTimeLessThanOrEqualTo(Date value) {
            addCriterion("cp_time <=", value, "cpTime");
            return (Criteria) this;
        }

        public Criteria andCpTimeIn(List<Date> values) {
            addCriterion("cp_time in", values, "cpTime");
            return (Criteria) this;
        }

        public Criteria andCpTimeNotIn(List<Date> values) {
            addCriterion("cp_time not in", values, "cpTime");
            return (Criteria) this;
        }

        public Criteria andCpTimeBetween(Date value1, Date value2) {
            addCriterion("cp_time between", value1, value2, "cpTime");
            return (Criteria) this;
        }

        public Criteria andCpTimeNotBetween(Date value1, Date value2) {
            addCriterion("cp_time not between", value1, value2, "cpTime");
            return (Criteria) this;
        }

        public Criteria andCpMoneyIsNull() {
            addCriterion("cp_money is null");
            return (Criteria) this;
        }

        public Criteria andCpMoneyIsNotNull() {
            addCriterion("cp_money is not null");
            return (Criteria) this;
        }

        public Criteria andCpMoneyEqualTo(BigDecimal value) {
            addCriterion("cp_money =", value, "cpMoney");
            return (Criteria) this;
        }

        public Criteria andCpMoneyNotEqualTo(BigDecimal value) {
            addCriterion("cp_money <>", value, "cpMoney");
            return (Criteria) this;
        }

        public Criteria andCpMoneyGreaterThan(BigDecimal value) {
            addCriterion("cp_money >", value, "cpMoney");
            return (Criteria) this;
        }

        public Criteria andCpMoneyGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("cp_money >=", value, "cpMoney");
            return (Criteria) this;
        }

        public Criteria andCpMoneyLessThan(BigDecimal value) {
            addCriterion("cp_money <", value, "cpMoney");
            return (Criteria) this;
        }

        public Criteria andCpMoneyLessThanOrEqualTo(BigDecimal value) {
            addCriterion("cp_money <=", value, "cpMoney");
            return (Criteria) this;
        }

        public Criteria andCpMoneyIn(List<BigDecimal> values) {
            addCriterion("cp_money in", values, "cpMoney");
            return (Criteria) this;
        }

        public Criteria andCpMoneyNotIn(List<BigDecimal> values) {
            addCriterion("cp_money not in", values, "cpMoney");
            return (Criteria) this;
        }

        public Criteria andCpMoneyBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("cp_money between", value1, value2, "cpMoney");
            return (Criteria) this;
        }

        public Criteria andCpMoneyNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("cp_money not between", value1, value2, "cpMoney");
            return (Criteria) this;
        }

        public Criteria andPaidTimeIsNull() {
            addCriterion("paid_time is null");
            return (Criteria) this;
        }

        public Criteria andPaidTimeIsNotNull() {
            addCriterion("paid_time is not null");
            return (Criteria) this;
        }

        public Criteria andPaidTimeEqualTo(Date value) {
            addCriterion("paid_time =", value, "paidTime");
            return (Criteria) this;
        }

        public Criteria andPaidTimeNotEqualTo(Date value) {
            addCriterion("paid_time <>", value, "paidTime");
            return (Criteria) this;
        }

        public Criteria andPaidTimeGreaterThan(Date value) {
            addCriterion("paid_time >", value, "paidTime");
            return (Criteria) this;
        }

        public Criteria andPaidTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("paid_time >=", value, "paidTime");
            return (Criteria) this;
        }

        public Criteria andPaidTimeLessThan(Date value) {
            addCriterion("paid_time <", value, "paidTime");
            return (Criteria) this;
        }

        public Criteria andPaidTimeLessThanOrEqualTo(Date value) {
            addCriterion("paid_time <=", value, "paidTime");
            return (Criteria) this;
        }

        public Criteria andPaidTimeIn(List<Date> values) {
            addCriterion("paid_time in", values, "paidTime");
            return (Criteria) this;
        }

        public Criteria andPaidTimeNotIn(List<Date> values) {
            addCriterion("paid_time not in", values, "paidTime");
            return (Criteria) this;
        }

        public Criteria andPaidTimeBetween(Date value1, Date value2) {
            addCriterion("paid_time between", value1, value2, "paidTime");
            return (Criteria) this;
        }

        public Criteria andPaidTimeNotBetween(Date value1, Date value2) {
            addCriterion("paid_time not between", value1, value2, "paidTime");
            return (Criteria) this;
        }

        public Criteria andPaidNumIsNull() {
            addCriterion("paid_num is null");
            return (Criteria) this;
        }

        public Criteria andPaidNumIsNotNull() {
            addCriterion("paid_num is not null");
            return (Criteria) this;
        }

        public Criteria andPaidNumEqualTo(BigDecimal value) {
            addCriterion("paid_num =", value, "paidNum");
            return (Criteria) this;
        }

        public Criteria andPaidNumNotEqualTo(BigDecimal value) {
            addCriterion("paid_num <>", value, "paidNum");
            return (Criteria) this;
        }

        public Criteria andPaidNumGreaterThan(BigDecimal value) {
            addCriterion("paid_num >", value, "paidNum");
            return (Criteria) this;
        }

        public Criteria andPaidNumGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("paid_num >=", value, "paidNum");
            return (Criteria) this;
        }

        public Criteria andPaidNumLessThan(BigDecimal value) {
            addCriterion("paid_num <", value, "paidNum");
            return (Criteria) this;
        }

        public Criteria andPaidNumLessThanOrEqualTo(BigDecimal value) {
            addCriterion("paid_num <=", value, "paidNum");
            return (Criteria) this;
        }

        public Criteria andPaidNumIn(List<BigDecimal> values) {
            addCriterion("paid_num in", values, "paidNum");
            return (Criteria) this;
        }

        public Criteria andPaidNumNotIn(List<BigDecimal> values) {
            addCriterion("paid_num not in", values, "paidNum");
            return (Criteria) this;
        }

        public Criteria andPaidNumBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("paid_num between", value1, value2, "paidNum");
            return (Criteria) this;
        }

        public Criteria andPaidNumNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("paid_num not between", value1, value2, "paidNum");
            return (Criteria) this;
        }

        public Criteria andSurUserIsNull() {
            addCriterion("sur_user is null");
            return (Criteria) this;
        }

        public Criteria andSurUserIsNotNull() {
            addCriterion("sur_user is not null");
            return (Criteria) this;
        }

        public Criteria andSurUserEqualTo(String value) {
            addCriterion("sur_user =", value, "surUser");
            return (Criteria) this;
        }

        public Criteria andSurUserNotEqualTo(String value) {
            addCriterion("sur_user <>", value, "surUser");
            return (Criteria) this;
        }

        public Criteria andSurUserGreaterThan(String value) {
            addCriterion("sur_user >", value, "surUser");
            return (Criteria) this;
        }

        public Criteria andSurUserGreaterThanOrEqualTo(String value) {
            addCriterion("sur_user >=", value, "surUser");
            return (Criteria) this;
        }

        public Criteria andSurUserLessThan(String value) {
            addCriterion("sur_user <", value, "surUser");
            return (Criteria) this;
        }

        public Criteria andSurUserLessThanOrEqualTo(String value) {
            addCriterion("sur_user <=", value, "surUser");
            return (Criteria) this;
        }

        public Criteria andSurUserLike(String value) {
            addCriterion("sur_user like", value, "surUser");
            return (Criteria) this;
        }

        public Criteria andSurUserNotLike(String value) {
            addCriterion("sur_user not like", value, "surUser");
            return (Criteria) this;
        }

        public Criteria andSurUserIn(List<String> values) {
            addCriterion("sur_user in", values, "surUser");
            return (Criteria) this;
        }

        public Criteria andSurUserNotIn(List<String> values) {
            addCriterion("sur_user not in", values, "surUser");
            return (Criteria) this;
        }

        public Criteria andSurUserBetween(String value1, String value2) {
            addCriterion("sur_user between", value1, value2, "surUser");
            return (Criteria) this;
        }

        public Criteria andSurUserNotBetween(String value1, String value2) {
            addCriterion("sur_user not between", value1, value2, "surUser");
            return (Criteria) this;
        }

        public Criteria andSurTimeIsNull() {
            addCriterion("sur_time is null");
            return (Criteria) this;
        }

        public Criteria andSurTimeIsNotNull() {
            addCriterion("sur_time is not null");
            return (Criteria) this;
        }

        public Criteria andSurTimeEqualTo(Date value) {
            addCriterion("sur_time =", value, "surTime");
            return (Criteria) this;
        }

        public Criteria andSurTimeNotEqualTo(Date value) {
            addCriterion("sur_time <>", value, "surTime");
            return (Criteria) this;
        }

        public Criteria andSurTimeGreaterThan(Date value) {
            addCriterion("sur_time >", value, "surTime");
            return (Criteria) this;
        }

        public Criteria andSurTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("sur_time >=", value, "surTime");
            return (Criteria) this;
        }

        public Criteria andSurTimeLessThan(Date value) {
            addCriterion("sur_time <", value, "surTime");
            return (Criteria) this;
        }

        public Criteria andSurTimeLessThanOrEqualTo(Date value) {
            addCriterion("sur_time <=", value, "surTime");
            return (Criteria) this;
        }

        public Criteria andSurTimeIn(List<Date> values) {
            addCriterion("sur_time in", values, "surTime");
            return (Criteria) this;
        }

        public Criteria andSurTimeNotIn(List<Date> values) {
            addCriterion("sur_time not in", values, "surTime");
            return (Criteria) this;
        }

        public Criteria andSurTimeBetween(Date value1, Date value2) {
            addCriterion("sur_time between", value1, value2, "surTime");
            return (Criteria) this;
        }

        public Criteria andSurTimeNotBetween(Date value1, Date value2) {
            addCriterion("sur_time not between", value1, value2, "surTime");
            return (Criteria) this;
        }

        public Criteria andDelUserIsNull() {
            addCriterion("del_user is null");
            return (Criteria) this;
        }

        public Criteria andDelUserIsNotNull() {
            addCriterion("del_user is not null");
            return (Criteria) this;
        }

        public Criteria andDelUserEqualTo(String value) {
            addCriterion("del_user =", value, "delUser");
            return (Criteria) this;
        }

        public Criteria andDelUserNotEqualTo(String value) {
            addCriterion("del_user <>", value, "delUser");
            return (Criteria) this;
        }

        public Criteria andDelUserGreaterThan(String value) {
            addCriterion("del_user >", value, "delUser");
            return (Criteria) this;
        }

        public Criteria andDelUserGreaterThanOrEqualTo(String value) {
            addCriterion("del_user >=", value, "delUser");
            return (Criteria) this;
        }

        public Criteria andDelUserLessThan(String value) {
            addCriterion("del_user <", value, "delUser");
            return (Criteria) this;
        }

        public Criteria andDelUserLessThanOrEqualTo(String value) {
            addCriterion("del_user <=", value, "delUser");
            return (Criteria) this;
        }

        public Criteria andDelUserLike(String value) {
            addCriterion("del_user like", value, "delUser");
            return (Criteria) this;
        }

        public Criteria andDelUserNotLike(String value) {
            addCriterion("del_user not like", value, "delUser");
            return (Criteria) this;
        }

        public Criteria andDelUserIn(List<String> values) {
            addCriterion("del_user in", values, "delUser");
            return (Criteria) this;
        }

        public Criteria andDelUserNotIn(List<String> values) {
            addCriterion("del_user not in", values, "delUser");
            return (Criteria) this;
        }

        public Criteria andDelUserBetween(String value1, String value2) {
            addCriterion("del_user between", value1, value2, "delUser");
            return (Criteria) this;
        }

        public Criteria andDelUserNotBetween(String value1, String value2) {
            addCriterion("del_user not between", value1, value2, "delUser");
            return (Criteria) this;
        }

        public Criteria andDelTimeIsNull() {
            addCriterion("del_time is null");
            return (Criteria) this;
        }

        public Criteria andDelTimeIsNotNull() {
            addCriterion("del_time is not null");
            return (Criteria) this;
        }

        public Criteria andDelTimeEqualTo(Date value) {
            addCriterion("del_time =", value, "delTime");
            return (Criteria) this;
        }

        public Criteria andDelTimeNotEqualTo(Date value) {
            addCriterion("del_time <>", value, "delTime");
            return (Criteria) this;
        }

        public Criteria andDelTimeGreaterThan(Date value) {
            addCriterion("del_time >", value, "delTime");
            return (Criteria) this;
        }

        public Criteria andDelTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("del_time >=", value, "delTime");
            return (Criteria) this;
        }

        public Criteria andDelTimeLessThan(Date value) {
            addCriterion("del_time <", value, "delTime");
            return (Criteria) this;
        }

        public Criteria andDelTimeLessThanOrEqualTo(Date value) {
            addCriterion("del_time <=", value, "delTime");
            return (Criteria) this;
        }

        public Criteria andDelTimeIn(List<Date> values) {
            addCriterion("del_time in", values, "delTime");
            return (Criteria) this;
        }

        public Criteria andDelTimeNotIn(List<Date> values) {
            addCriterion("del_time not in", values, "delTime");
            return (Criteria) this;
        }

        public Criteria andDelTimeBetween(Date value1, Date value2) {
            addCriterion("del_time between", value1, value2, "delTime");
            return (Criteria) this;
        }

        public Criteria andDelTimeNotBetween(Date value1, Date value2) {
            addCriterion("del_time not between", value1, value2, "delTime");
            return (Criteria) this;
        }

        public Criteria andMPaidIsNull() {
            addCriterion("m_paid is null");
            return (Criteria) this;
        }

        public Criteria andMPaidIsNotNull() {
            addCriterion("m_paid is not null");
            return (Criteria) this;
        }

        public Criteria andMPaidEqualTo(BigDecimal value) {
            addCriterion("m_paid =", value, "mPaid");
            return (Criteria) this;
        }

        public Criteria andMPaidNotEqualTo(BigDecimal value) {
            addCriterion("m_paid <>", value, "mPaid");
            return (Criteria) this;
        }

        public Criteria andMPaidGreaterThan(BigDecimal value) {
            addCriterion("m_paid >", value, "mPaid");
            return (Criteria) this;
        }

        public Criteria andMPaidGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("m_paid >=", value, "mPaid");
            return (Criteria) this;
        }

        public Criteria andMPaidLessThan(BigDecimal value) {
            addCriterion("m_paid <", value, "mPaid");
            return (Criteria) this;
        }

        public Criteria andMPaidLessThanOrEqualTo(BigDecimal value) {
            addCriterion("m_paid <=", value, "mPaid");
            return (Criteria) this;
        }

        public Criteria andMPaidIn(List<BigDecimal> values) {
            addCriterion("m_paid in", values, "mPaid");
            return (Criteria) this;
        }

        public Criteria andMPaidNotIn(List<BigDecimal> values) {
            addCriterion("m_paid not in", values, "mPaid");
            return (Criteria) this;
        }

        public Criteria andMPaidBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("m_paid between", value1, value2, "mPaid");
            return (Criteria) this;
        }

        public Criteria andMPaidNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("m_paid not between", value1, value2, "mPaid");
            return (Criteria) this;
        }

        public Criteria andCpmPaidIsNull() {
            addCriterion("cpm_paid is null");
            return (Criteria) this;
        }

        public Criteria andCpmPaidIsNotNull() {
            addCriterion("cpm_paid is not null");
            return (Criteria) this;
        }

        public Criteria andCpmPaidEqualTo(BigDecimal value) {
            addCriterion("cpm_paid =", value, "cpmPaid");
            return (Criteria) this;
        }

        public Criteria andCpmPaidNotEqualTo(BigDecimal value) {
            addCriterion("cpm_paid <>", value, "cpmPaid");
            return (Criteria) this;
        }

        public Criteria andCpmPaidGreaterThan(BigDecimal value) {
            addCriterion("cpm_paid >", value, "cpmPaid");
            return (Criteria) this;
        }

        public Criteria andCpmPaidGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("cpm_paid >=", value, "cpmPaid");
            return (Criteria) this;
        }

        public Criteria andCpmPaidLessThan(BigDecimal value) {
            addCriterion("cpm_paid <", value, "cpmPaid");
            return (Criteria) this;
        }

        public Criteria andCpmPaidLessThanOrEqualTo(BigDecimal value) {
            addCriterion("cpm_paid <=", value, "cpmPaid");
            return (Criteria) this;
        }

        public Criteria andCpmPaidIn(List<BigDecimal> values) {
            addCriterion("cpm_paid in", values, "cpmPaid");
            return (Criteria) this;
        }

        public Criteria andCpmPaidNotIn(List<BigDecimal> values) {
            addCriterion("cpm_paid not in", values, "cpmPaid");
            return (Criteria) this;
        }

        public Criteria andCpmPaidBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("cpm_paid between", value1, value2, "cpmPaid");
            return (Criteria) this;
        }

        public Criteria andCpmPaidNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("cpm_paid not between", value1, value2, "cpmPaid");
            return (Criteria) this;
        }

        public Criteria andSeNoIsNull() {
            addCriterion("se_no is null");
            return (Criteria) this;
        }

        public Criteria andSeNoIsNotNull() {
            addCriterion("se_no is not null");
            return (Criteria) this;
        }

        public Criteria andSeNoEqualTo(String value) {
            addCriterion("se_no =", value, "seNo");
            return (Criteria) this;
        }

        public Criteria andSeNoNotEqualTo(String value) {
            addCriterion("se_no <>", value, "seNo");
            return (Criteria) this;
        }

        public Criteria andSeNoGreaterThan(String value) {
            addCriterion("se_no >", value, "seNo");
            return (Criteria) this;
        }

        public Criteria andSeNoGreaterThanOrEqualTo(String value) {
            addCriterion("se_no >=", value, "seNo");
            return (Criteria) this;
        }

        public Criteria andSeNoLessThan(String value) {
            addCriterion("se_no <", value, "seNo");
            return (Criteria) this;
        }

        public Criteria andSeNoLessThanOrEqualTo(String value) {
            addCriterion("se_no <=", value, "seNo");
            return (Criteria) this;
        }

        public Criteria andSeNoLike(String value) {
            addCriterion("se_no like", value, "seNo");
            return (Criteria) this;
        }

        public Criteria andSeNoNotLike(String value) {
            addCriterion("se_no not like", value, "seNo");
            return (Criteria) this;
        }

        public Criteria andSeNoIn(List<String> values) {
            addCriterion("se_no in", values, "seNo");
            return (Criteria) this;
        }

        public Criteria andSeNoNotIn(List<String> values) {
            addCriterion("se_no not in", values, "seNo");
            return (Criteria) this;
        }

        public Criteria andSeNoBetween(String value1, String value2) {
            addCriterion("se_no between", value1, value2, "seNo");
            return (Criteria) this;
        }

        public Criteria andSeNoNotBetween(String value1, String value2) {
            addCriterion("se_no not between", value1, value2, "seNo");
            return (Criteria) this;
        }

        public Criteria andCmPaidIsNull() {
            addCriterion("cm_paid is null");
            return (Criteria) this;
        }

        public Criteria andCmPaidIsNotNull() {
            addCriterion("cm_paid is not null");
            return (Criteria) this;
        }

        public Criteria andCmPaidEqualTo(BigDecimal value) {
            addCriterion("cm_paid =", value, "cmPaid");
            return (Criteria) this;
        }

        public Criteria andCmPaidNotEqualTo(BigDecimal value) {
            addCriterion("cm_paid <>", value, "cmPaid");
            return (Criteria) this;
        }

        public Criteria andCmPaidGreaterThan(BigDecimal value) {
            addCriterion("cm_paid >", value, "cmPaid");
            return (Criteria) this;
        }

        public Criteria andCmPaidGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("cm_paid >=", value, "cmPaid");
            return (Criteria) this;
        }

        public Criteria andCmPaidLessThan(BigDecimal value) {
            addCriterion("cm_paid <", value, "cmPaid");
            return (Criteria) this;
        }

        public Criteria andCmPaidLessThanOrEqualTo(BigDecimal value) {
            addCriterion("cm_paid <=", value, "cmPaid");
            return (Criteria) this;
        }

        public Criteria andCmPaidIn(List<BigDecimal> values) {
            addCriterion("cm_paid in", values, "cmPaid");
            return (Criteria) this;
        }

        public Criteria andCmPaidNotIn(List<BigDecimal> values) {
            addCriterion("cm_paid not in", values, "cmPaid");
            return (Criteria) this;
        }

        public Criteria andCmPaidBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("cm_paid between", value1, value2, "cmPaid");
            return (Criteria) this;
        }

        public Criteria andCmPaidNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("cm_paid not between", value1, value2, "cmPaid");
            return (Criteria) this;
        }

        public Criteria andBackPaidIsNull() {
            addCriterion("back_paid is null");
            return (Criteria) this;
        }

        public Criteria andBackPaidIsNotNull() {
            addCriterion("back_paid is not null");
            return (Criteria) this;
        }

        public Criteria andBackPaidEqualTo(BigDecimal value) {
            addCriterion("back_paid =", value, "backPaid");
            return (Criteria) this;
        }

        public Criteria andBackPaidNotEqualTo(BigDecimal value) {
            addCriterion("back_paid <>", value, "backPaid");
            return (Criteria) this;
        }

        public Criteria andBackPaidGreaterThan(BigDecimal value) {
            addCriterion("back_paid >", value, "backPaid");
            return (Criteria) this;
        }

        public Criteria andBackPaidGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("back_paid >=", value, "backPaid");
            return (Criteria) this;
        }

        public Criteria andBackPaidLessThan(BigDecimal value) {
            addCriterion("back_paid <", value, "backPaid");
            return (Criteria) this;
        }

        public Criteria andBackPaidLessThanOrEqualTo(BigDecimal value) {
            addCriterion("back_paid <=", value, "backPaid");
            return (Criteria) this;
        }

        public Criteria andBackPaidIn(List<BigDecimal> values) {
            addCriterion("back_paid in", values, "backPaid");
            return (Criteria) this;
        }

        public Criteria andBackPaidNotIn(List<BigDecimal> values) {
            addCriterion("back_paid not in", values, "backPaid");
            return (Criteria) this;
        }

        public Criteria andBackPaidBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("back_paid between", value1, value2, "backPaid");
            return (Criteria) this;
        }

        public Criteria andBackPaidNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("back_paid not between", value1, value2, "backPaid");
            return (Criteria) this;
        }

        public Criteria andBackPaidRateIsNull() {
            addCriterion("back_paid_rate is null");
            return (Criteria) this;
        }

        public Criteria andBackPaidRateIsNotNull() {
            addCriterion("back_paid_rate is not null");
            return (Criteria) this;
        }

        public Criteria andBackPaidRateEqualTo(BigDecimal value) {
            addCriterion("back_paid_rate =", value, "backPaidRate");
            return (Criteria) this;
        }

        public Criteria andBackPaidRateNotEqualTo(BigDecimal value) {
            addCriterion("back_paid_rate <>", value, "backPaidRate");
            return (Criteria) this;
        }

        public Criteria andBackPaidRateGreaterThan(BigDecimal value) {
            addCriterion("back_paid_rate >", value, "backPaidRate");
            return (Criteria) this;
        }

        public Criteria andBackPaidRateGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("back_paid_rate >=", value, "backPaidRate");
            return (Criteria) this;
        }

        public Criteria andBackPaidRateLessThan(BigDecimal value) {
            addCriterion("back_paid_rate <", value, "backPaidRate");
            return (Criteria) this;
        }

        public Criteria andBackPaidRateLessThanOrEqualTo(BigDecimal value) {
            addCriterion("back_paid_rate <=", value, "backPaidRate");
            return (Criteria) this;
        }

        public Criteria andBackPaidRateIn(List<BigDecimal> values) {
            addCriterion("back_paid_rate in", values, "backPaidRate");
            return (Criteria) this;
        }

        public Criteria andBackPaidRateNotIn(List<BigDecimal> values) {
            addCriterion("back_paid_rate not in", values, "backPaidRate");
            return (Criteria) this;
        }

        public Criteria andBackPaidRateBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("back_paid_rate between", value1, value2, "backPaidRate");
            return (Criteria) this;
        }

        public Criteria andBackPaidRateNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("back_paid_rate not between", value1, value2, "backPaidRate");
            return (Criteria) this;
        }

        public Criteria andPbackPaidIsNull() {
            addCriterion("pback_paid is null");
            return (Criteria) this;
        }

        public Criteria andPbackPaidIsNotNull() {
            addCriterion("pback_paid is not null");
            return (Criteria) this;
        }

        public Criteria andPbackPaidEqualTo(BigDecimal value) {
            addCriterion("pback_paid =", value, "pbackPaid");
            return (Criteria) this;
        }

        public Criteria andPbackPaidNotEqualTo(BigDecimal value) {
            addCriterion("pback_paid <>", value, "pbackPaid");
            return (Criteria) this;
        }

        public Criteria andPbackPaidGreaterThan(BigDecimal value) {
            addCriterion("pback_paid >", value, "pbackPaid");
            return (Criteria) this;
        }

        public Criteria andPbackPaidGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("pback_paid >=", value, "pbackPaid");
            return (Criteria) this;
        }

        public Criteria andPbackPaidLessThan(BigDecimal value) {
            addCriterion("pback_paid <", value, "pbackPaid");
            return (Criteria) this;
        }

        public Criteria andPbackPaidLessThanOrEqualTo(BigDecimal value) {
            addCriterion("pback_paid <=", value, "pbackPaid");
            return (Criteria) this;
        }

        public Criteria andPbackPaidIn(List<BigDecimal> values) {
            addCriterion("pback_paid in", values, "pbackPaid");
            return (Criteria) this;
        }

        public Criteria andPbackPaidNotIn(List<BigDecimal> values) {
            addCriterion("pback_paid not in", values, "pbackPaid");
            return (Criteria) this;
        }

        public Criteria andPbackPaidBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("pback_paid between", value1, value2, "pbackPaid");
            return (Criteria) this;
        }

        public Criteria andPbackPaidNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("pback_paid not between", value1, value2, "pbackPaid");
            return (Criteria) this;
        }

        public Criteria andEntrustPaidIsNull() {
            addCriterion("entrust_paid is null");
            return (Criteria) this;
        }

        public Criteria andEntrustPaidIsNotNull() {
            addCriterion("entrust_paid is not null");
            return (Criteria) this;
        }

        public Criteria andEntrustPaidEqualTo(BigDecimal value) {
            addCriterion("entrust_paid =", value, "entrustPaid");
            return (Criteria) this;
        }

        public Criteria andEntrustPaidNotEqualTo(BigDecimal value) {
            addCriterion("entrust_paid <>", value, "entrustPaid");
            return (Criteria) this;
        }

        public Criteria andEntrustPaidGreaterThan(BigDecimal value) {
            addCriterion("entrust_paid >", value, "entrustPaid");
            return (Criteria) this;
        }

        public Criteria andEntrustPaidGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("entrust_paid >=", value, "entrustPaid");
            return (Criteria) this;
        }

        public Criteria andEntrustPaidLessThan(BigDecimal value) {
            addCriterion("entrust_paid <", value, "entrustPaid");
            return (Criteria) this;
        }

        public Criteria andEntrustPaidLessThanOrEqualTo(BigDecimal value) {
            addCriterion("entrust_paid <=", value, "entrustPaid");
            return (Criteria) this;
        }

        public Criteria andEntrustPaidIn(List<BigDecimal> values) {
            addCriterion("entrust_paid in", values, "entrustPaid");
            return (Criteria) this;
        }

        public Criteria andEntrustPaidNotIn(List<BigDecimal> values) {
            addCriterion("entrust_paid not in", values, "entrustPaid");
            return (Criteria) this;
        }

        public Criteria andEntrustPaidBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("entrust_paid between", value1, value2, "entrustPaid");
            return (Criteria) this;
        }

        public Criteria andEntrustPaidNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("entrust_paid not between", value1, value2, "entrustPaid");
            return (Criteria) this;
        }

        public Criteria andEntrustPaidRateIsNull() {
            addCriterion("entrust_paid_rate is null");
            return (Criteria) this;
        }

        public Criteria andEntrustPaidRateIsNotNull() {
            addCriterion("entrust_paid_rate is not null");
            return (Criteria) this;
        }

        public Criteria andEntrustPaidRateEqualTo(BigDecimal value) {
            addCriterion("entrust_paid_rate =", value, "entrustPaidRate");
            return (Criteria) this;
        }

        public Criteria andEntrustPaidRateNotEqualTo(BigDecimal value) {
            addCriterion("entrust_paid_rate <>", value, "entrustPaidRate");
            return (Criteria) this;
        }

        public Criteria andEntrustPaidRateGreaterThan(BigDecimal value) {
            addCriterion("entrust_paid_rate >", value, "entrustPaidRate");
            return (Criteria) this;
        }

        public Criteria andEntrustPaidRateGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("entrust_paid_rate >=", value, "entrustPaidRate");
            return (Criteria) this;
        }

        public Criteria andEntrustPaidRateLessThan(BigDecimal value) {
            addCriterion("entrust_paid_rate <", value, "entrustPaidRate");
            return (Criteria) this;
        }

        public Criteria andEntrustPaidRateLessThanOrEqualTo(BigDecimal value) {
            addCriterion("entrust_paid_rate <=", value, "entrustPaidRate");
            return (Criteria) this;
        }

        public Criteria andEntrustPaidRateIn(List<BigDecimal> values) {
            addCriterion("entrust_paid_rate in", values, "entrustPaidRate");
            return (Criteria) this;
        }

        public Criteria andEntrustPaidRateNotIn(List<BigDecimal> values) {
            addCriterion("entrust_paid_rate not in", values, "entrustPaidRate");
            return (Criteria) this;
        }

        public Criteria andEntrustPaidRateBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("entrust_paid_rate between", value1, value2, "entrustPaidRate");
            return (Criteria) this;
        }

        public Criteria andEntrustPaidRateNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("entrust_paid_rate not between", value1, value2, "entrustPaidRate");
            return (Criteria) this;
        }

        public Criteria andLastDebtMIsNull() {
            addCriterion("last_debt_m is null");
            return (Criteria) this;
        }

        public Criteria andLastDebtMIsNotNull() {
            addCriterion("last_debt_m is not null");
            return (Criteria) this;
        }

        public Criteria andLastDebtMEqualTo(BigDecimal value) {
            addCriterion("last_debt_m =", value, "lastDebtM");
            return (Criteria) this;
        }

        public Criteria andLastDebtMNotEqualTo(BigDecimal value) {
            addCriterion("last_debt_m <>", value, "lastDebtM");
            return (Criteria) this;
        }

        public Criteria andLastDebtMGreaterThan(BigDecimal value) {
            addCriterion("last_debt_m >", value, "lastDebtM");
            return (Criteria) this;
        }

        public Criteria andLastDebtMGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("last_debt_m >=", value, "lastDebtM");
            return (Criteria) this;
        }

        public Criteria andLastDebtMLessThan(BigDecimal value) {
            addCriterion("last_debt_m <", value, "lastDebtM");
            return (Criteria) this;
        }

        public Criteria andLastDebtMLessThanOrEqualTo(BigDecimal value) {
            addCriterion("last_debt_m <=", value, "lastDebtM");
            return (Criteria) this;
        }

        public Criteria andLastDebtMIn(List<BigDecimal> values) {
            addCriterion("last_debt_m in", values, "lastDebtM");
            return (Criteria) this;
        }

        public Criteria andLastDebtMNotIn(List<BigDecimal> values) {
            addCriterion("last_debt_m not in", values, "lastDebtM");
            return (Criteria) this;
        }

        public Criteria andLastDebtMBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("last_debt_m between", value1, value2, "lastDebtM");
            return (Criteria) this;
        }

        public Criteria andLastDebtMNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("last_debt_m not between", value1, value2, "lastDebtM");
            return (Criteria) this;
        }

        public Criteria andLeftAmtIsNull() {
            addCriterion("left_amt is null");
            return (Criteria) this;
        }

        public Criteria andLeftAmtIsNotNull() {
            addCriterion("left_amt is not null");
            return (Criteria) this;
        }

        public Criteria andLeftAmtEqualTo(BigDecimal value) {
            addCriterion("left_amt =", value, "leftAmt");
            return (Criteria) this;
        }

        public Criteria andLeftAmtNotEqualTo(BigDecimal value) {
            addCriterion("left_amt <>", value, "leftAmt");
            return (Criteria) this;
        }

        public Criteria andLeftAmtGreaterThan(BigDecimal value) {
            addCriterion("left_amt >", value, "leftAmt");
            return (Criteria) this;
        }

        public Criteria andLeftAmtGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("left_amt >=", value, "leftAmt");
            return (Criteria) this;
        }

        public Criteria andLeftAmtLessThan(BigDecimal value) {
            addCriterion("left_amt <", value, "leftAmt");
            return (Criteria) this;
        }

        public Criteria andLeftAmtLessThanOrEqualTo(BigDecimal value) {
            addCriterion("left_amt <=", value, "leftAmt");
            return (Criteria) this;
        }

        public Criteria andLeftAmtIn(List<BigDecimal> values) {
            addCriterion("left_amt in", values, "leftAmt");
            return (Criteria) this;
        }

        public Criteria andLeftAmtNotIn(List<BigDecimal> values) {
            addCriterion("left_amt not in", values, "leftAmt");
            return (Criteria) this;
        }

        public Criteria andLeftAmtBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("left_amt between", value1, value2, "leftAmt");
            return (Criteria) this;
        }

        public Criteria andLeftAmtNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("left_amt not between", value1, value2, "leftAmt");
            return (Criteria) this;
        }

        public Criteria andCreateEmpIdIsNull() {
            addCriterion("create_emp_id is null");
            return (Criteria) this;
        }

        public Criteria andCreateEmpIdIsNotNull() {
            addCriterion("create_emp_id is not null");
            return (Criteria) this;
        }

        public Criteria andCreateEmpIdEqualTo(String value) {
            addCriterion("create_emp_id =", value, "createEmpId");
            return (Criteria) this;
        }

        public Criteria andCreateEmpIdNotEqualTo(String value) {
            addCriterion("create_emp_id <>", value, "createEmpId");
            return (Criteria) this;
        }

        public Criteria andCreateEmpIdGreaterThan(String value) {
            addCriterion("create_emp_id >", value, "createEmpId");
            return (Criteria) this;
        }

        public Criteria andCreateEmpIdGreaterThanOrEqualTo(String value) {
            addCriterion("create_emp_id >=", value, "createEmpId");
            return (Criteria) this;
        }

        public Criteria andCreateEmpIdLessThan(String value) {
            addCriterion("create_emp_id <", value, "createEmpId");
            return (Criteria) this;
        }

        public Criteria andCreateEmpIdLessThanOrEqualTo(String value) {
            addCriterion("create_emp_id <=", value, "createEmpId");
            return (Criteria) this;
        }

        public Criteria andCreateEmpIdLike(String value) {
            addCriterion("create_emp_id like", value, "createEmpId");
            return (Criteria) this;
        }

        public Criteria andCreateEmpIdNotLike(String value) {
            addCriterion("create_emp_id not like", value, "createEmpId");
            return (Criteria) this;
        }

        public Criteria andCreateEmpIdIn(List<String> values) {
            addCriterion("create_emp_id in", values, "createEmpId");
            return (Criteria) this;
        }

        public Criteria andCreateEmpIdNotIn(List<String> values) {
            addCriterion("create_emp_id not in", values, "createEmpId");
            return (Criteria) this;
        }

        public Criteria andCreateEmpIdBetween(String value1, String value2) {
            addCriterion("create_emp_id between", value1, value2, "createEmpId");
            return (Criteria) this;
        }

        public Criteria andCreateEmpIdNotBetween(String value1, String value2) {
            addCriterion("create_emp_id not between", value1, value2, "createEmpId");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andModifyEmpIdIsNull() {
            addCriterion("modify_emp_id is null");
            return (Criteria) this;
        }

        public Criteria andModifyEmpIdIsNotNull() {
            addCriterion("modify_emp_id is not null");
            return (Criteria) this;
        }

        public Criteria andModifyEmpIdEqualTo(String value) {
            addCriterion("modify_emp_id =", value, "modifyEmpId");
            return (Criteria) this;
        }

        public Criteria andModifyEmpIdNotEqualTo(String value) {
            addCriterion("modify_emp_id <>", value, "modifyEmpId");
            return (Criteria) this;
        }

        public Criteria andModifyEmpIdGreaterThan(String value) {
            addCriterion("modify_emp_id >", value, "modifyEmpId");
            return (Criteria) this;
        }

        public Criteria andModifyEmpIdGreaterThanOrEqualTo(String value) {
            addCriterion("modify_emp_id >=", value, "modifyEmpId");
            return (Criteria) this;
        }

        public Criteria andModifyEmpIdLessThan(String value) {
            addCriterion("modify_emp_id <", value, "modifyEmpId");
            return (Criteria) this;
        }

        public Criteria andModifyEmpIdLessThanOrEqualTo(String value) {
            addCriterion("modify_emp_id <=", value, "modifyEmpId");
            return (Criteria) this;
        }

        public Criteria andModifyEmpIdLike(String value) {
            addCriterion("modify_emp_id like", value, "modifyEmpId");
            return (Criteria) this;
        }

        public Criteria andModifyEmpIdNotLike(String value) {
            addCriterion("modify_emp_id not like", value, "modifyEmpId");
            return (Criteria) this;
        }

        public Criteria andModifyEmpIdIn(List<String> values) {
            addCriterion("modify_emp_id in", values, "modifyEmpId");
            return (Criteria) this;
        }

        public Criteria andModifyEmpIdNotIn(List<String> values) {
            addCriterion("modify_emp_id not in", values, "modifyEmpId");
            return (Criteria) this;
        }

        public Criteria andModifyEmpIdBetween(String value1, String value2) {
            addCriterion("modify_emp_id between", value1, value2, "modifyEmpId");
            return (Criteria) this;
        }

        public Criteria andModifyEmpIdNotBetween(String value1, String value2) {
            addCriterion("modify_emp_id not between", value1, value2, "modifyEmpId");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIsNull() {
            addCriterion("modify_time is null");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIsNotNull() {
            addCriterion("modify_time is not null");
            return (Criteria) this;
        }

        public Criteria andModifyTimeEqualTo(Date value) {
            addCriterion("modify_time =", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotEqualTo(Date value) {
            addCriterion("modify_time <>", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeGreaterThan(Date value) {
            addCriterion("modify_time >", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("modify_time >=", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeLessThan(Date value) {
            addCriterion("modify_time <", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeLessThanOrEqualTo(Date value) {
            addCriterion("modify_time <=", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIn(List<Date> values) {
            addCriterion("modify_time in", values, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotIn(List<Date> values) {
            addCriterion("modify_time not in", values, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeBetween(Date value1, Date value2) {
            addCriterion("modify_time between", value1, value2, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotBetween(Date value1, Date value2) {
            addCriterion("modify_time not between", value1, value2, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andVersionIsNull() {
            addCriterion("version is null");
            return (Criteria) this;
        }

        public Criteria andVersionIsNotNull() {
            addCriterion("version is not null");
            return (Criteria) this;
        }

        public Criteria andVersionEqualTo(Integer value) {
            addCriterion("version =", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotEqualTo(Integer value) {
            addCriterion("version <>", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThan(Integer value) {
            addCriterion("version >", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThanOrEqualTo(Integer value) {
            addCriterion("version >=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThan(Integer value) {
            addCriterion("version <", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThanOrEqualTo(Integer value) {
            addCriterion("version <=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionIn(List<Integer> values) {
            addCriterion("version in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotIn(List<Integer> values) {
            addCriterion("version not in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionBetween(Integer value1, Integer value2) {
            addCriterion("version between", value1, value2, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotBetween(Integer value1, Integer value2) {
            addCriterion("version not between", value1, value2, "version");
            return (Criteria) this;
        }

        public Criteria andIsDerateIsNull() {
            addCriterion("is_derate is null");
            return (Criteria) this;
        }

        public Criteria andIsDerateIsNotNull() {
            addCriterion("is_derate is not null");
            return (Criteria) this;
        }

        public Criteria andIsDerateEqualTo(String value) {
            addCriterion("is_derate =", value, "isDerate");
            return (Criteria) this;
        }

        public Criteria andIsDerateNotEqualTo(String value) {
            addCriterion("is_derate <>", value, "isDerate");
            return (Criteria) this;
        }

        public Criteria andIsDerateGreaterThan(String value) {
            addCriterion("is_derate >", value, "isDerate");
            return (Criteria) this;
        }

        public Criteria andIsDerateGreaterThanOrEqualTo(String value) {
            addCriterion("is_derate >=", value, "isDerate");
            return (Criteria) this;
        }

        public Criteria andIsDerateLessThan(String value) {
            addCriterion("is_derate <", value, "isDerate");
            return (Criteria) this;
        }

        public Criteria andIsDerateLessThanOrEqualTo(String value) {
            addCriterion("is_derate <=", value, "isDerate");
            return (Criteria) this;
        }

        public Criteria andIsDerateLike(String value) {
            addCriterion("is_derate like", value, "isDerate");
            return (Criteria) this;
        }

        public Criteria andIsDerateNotLike(String value) {
            addCriterion("is_derate not like", value, "isDerate");
            return (Criteria) this;
        }

        public Criteria andIsDerateIn(List<String> values) {
            addCriterion("is_derate in", values, "isDerate");
            return (Criteria) this;
        }

        public Criteria andIsDerateNotIn(List<String> values) {
            addCriterion("is_derate not in", values, "isDerate");
            return (Criteria) this;
        }

        public Criteria andIsDerateBetween(String value1, String value2) {
            addCriterion("is_derate between", value1, value2, "isDerate");
            return (Criteria) this;
        }

        public Criteria andIsDerateNotBetween(String value1, String value2) {
            addCriterion("is_derate not between", value1, value2, "isDerate");
            return (Criteria) this;
        }

        public Criteria andInDerateIsNull() {
            addCriterion("in_derate is null");
            return (Criteria) this;
        }

        public Criteria andInDerateIsNotNull() {
            addCriterion("in_derate is not null");
            return (Criteria) this;
        }

        public Criteria andInDerateEqualTo(BigDecimal value) {
            addCriterion("in_derate =", value, "inDerate");
            return (Criteria) this;
        }

        public Criteria andInDerateNotEqualTo(BigDecimal value) {
            addCriterion("in_derate <>", value, "inDerate");
            return (Criteria) this;
        }

        public Criteria andInDerateGreaterThan(BigDecimal value) {
            addCriterion("in_derate >", value, "inDerate");
            return (Criteria) this;
        }

        public Criteria andInDerateGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("in_derate >=", value, "inDerate");
            return (Criteria) this;
        }

        public Criteria andInDerateLessThan(BigDecimal value) {
            addCriterion("in_derate <", value, "inDerate");
            return (Criteria) this;
        }

        public Criteria andInDerateLessThanOrEqualTo(BigDecimal value) {
            addCriterion("in_derate <=", value, "inDerate");
            return (Criteria) this;
        }

        public Criteria andInDerateIn(List<BigDecimal> values) {
            addCriterion("in_derate in", values, "inDerate");
            return (Criteria) this;
        }

        public Criteria andInDerateNotIn(List<BigDecimal> values) {
            addCriterion("in_derate not in", values, "inDerate");
            return (Criteria) this;
        }

        public Criteria andInDerateBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("in_derate between", value1, value2, "inDerate");
            return (Criteria) this;
        }

        public Criteria andInDerateNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("in_derate not between", value1, value2, "inDerate");
            return (Criteria) this;
        }

        public Criteria andOutDerateIsNull() {
            addCriterion("out_derate is null");
            return (Criteria) this;
        }

        public Criteria andOutDerateIsNotNull() {
            addCriterion("out_derate is not null");
            return (Criteria) this;
        }

        public Criteria andOutDerateEqualTo(BigDecimal value) {
            addCriterion("out_derate =", value, "outDerate");
            return (Criteria) this;
        }

        public Criteria andOutDerateNotEqualTo(BigDecimal value) {
            addCriterion("out_derate <>", value, "outDerate");
            return (Criteria) this;
        }

        public Criteria andOutDerateGreaterThan(BigDecimal value) {
            addCriterion("out_derate >", value, "outDerate");
            return (Criteria) this;
        }

        public Criteria andOutDerateGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("out_derate >=", value, "outDerate");
            return (Criteria) this;
        }

        public Criteria andOutDerateLessThan(BigDecimal value) {
            addCriterion("out_derate <", value, "outDerate");
            return (Criteria) this;
        }

        public Criteria andOutDerateLessThanOrEqualTo(BigDecimal value) {
            addCriterion("out_derate <=", value, "outDerate");
            return (Criteria) this;
        }

        public Criteria andOutDerateIn(List<BigDecimal> values) {
            addCriterion("out_derate in", values, "outDerate");
            return (Criteria) this;
        }

        public Criteria andOutDerateNotIn(List<BigDecimal> values) {
            addCriterion("out_derate not in", values, "outDerate");
            return (Criteria) this;
        }

        public Criteria andOutDerateBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("out_derate between", value1, value2, "outDerate");
            return (Criteria) this;
        }

        public Criteria andOutDerateNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("out_derate not between", value1, value2, "outDerate");
            return (Criteria) this;
        }

        public Criteria andCancelReasonIsNull() {
            addCriterion("cancel_reason is null");
            return (Criteria) this;
        }

        public Criteria andCancelReasonIsNotNull() {
            addCriterion("cancel_reason is not null");
            return (Criteria) this;
        }

        public Criteria andCancelReasonEqualTo(String value) {
            addCriterion("cancel_reason =", value, "cancelReason");
            return (Criteria) this;
        }

        public Criteria andCancelReasonNotEqualTo(String value) {
            addCriterion("cancel_reason <>", value, "cancelReason");
            return (Criteria) this;
        }

        public Criteria andCancelReasonGreaterThan(String value) {
            addCriterion("cancel_reason >", value, "cancelReason");
            return (Criteria) this;
        }

        public Criteria andCancelReasonGreaterThanOrEqualTo(String value) {
            addCriterion("cancel_reason >=", value, "cancelReason");
            return (Criteria) this;
        }

        public Criteria andCancelReasonLessThan(String value) {
            addCriterion("cancel_reason <", value, "cancelReason");
            return (Criteria) this;
        }

        public Criteria andCancelReasonLessThanOrEqualTo(String value) {
            addCriterion("cancel_reason <=", value, "cancelReason");
            return (Criteria) this;
        }

        public Criteria andCancelReasonLike(String value) {
            addCriterion("cancel_reason like", value, "cancelReason");
            return (Criteria) this;
        }

        public Criteria andCancelReasonNotLike(String value) {
            addCriterion("cancel_reason not like", value, "cancelReason");
            return (Criteria) this;
        }

        public Criteria andCancelReasonIn(List<String> values) {
            addCriterion("cancel_reason in", values, "cancelReason");
            return (Criteria) this;
        }

        public Criteria andCancelReasonNotIn(List<String> values) {
            addCriterion("cancel_reason not in", values, "cancelReason");
            return (Criteria) this;
        }

        public Criteria andCancelReasonBetween(String value1, String value2) {
            addCriterion("cancel_reason between", value1, value2, "cancelReason");
            return (Criteria) this;
        }

        public Criteria andCancelReasonNotBetween(String value1, String value2) {
            addCriterion("cancel_reason not between", value1, value2, "cancelReason");
            return (Criteria) this;
        }

        public Criteria andRepayTypeIsNull() {
            addCriterion("repay_type is null");
            return (Criteria) this;
        }

        public Criteria andRepayTypeIsNotNull() {
            addCriterion("repay_type is not null");
            return (Criteria) this;
        }

        public Criteria andRepayTypeEqualTo(String value) {
            addCriterion("repay_type =", value, "repayType");
            return (Criteria) this;
        }

        public Criteria andRepayTypeNotEqualTo(String value) {
            addCriterion("repay_type <>", value, "repayType");
            return (Criteria) this;
        }

        public Criteria andRepayTypeGreaterThan(String value) {
            addCriterion("repay_type >", value, "repayType");
            return (Criteria) this;
        }

        public Criteria andRepayTypeGreaterThanOrEqualTo(String value) {
            addCriterion("repay_type >=", value, "repayType");
            return (Criteria) this;
        }

        public Criteria andRepayTypeLessThan(String value) {
            addCriterion("repay_type <", value, "repayType");
            return (Criteria) this;
        }

        public Criteria andRepayTypeLessThanOrEqualTo(String value) {
            addCriterion("repay_type <=", value, "repayType");
            return (Criteria) this;
        }

        public Criteria andRepayTypeLike(String value) {
            addCriterion("repay_type like", value, "repayType");
            return (Criteria) this;
        }

        public Criteria andRepayTypeNotLike(String value) {
            addCriterion("repay_type not like", value, "repayType");
            return (Criteria) this;
        }

        public Criteria andRepayTypeIn(List<String> values) {
            addCriterion("repay_type in", values, "repayType");
            return (Criteria) this;
        }

        public Criteria andRepayTypeNotIn(List<String> values) {
            addCriterion("repay_type not in", values, "repayType");
            return (Criteria) this;
        }

        public Criteria andRepayTypeBetween(String value1, String value2) {
            addCriterion("repay_type between", value1, value2, "repayType");
            return (Criteria) this;
        }

        public Criteria andRepayTypeNotBetween(String value1, String value2) {
            addCriterion("repay_type not between", value1, value2, "repayType");
            return (Criteria) this;
        }

        public Criteria andOperateEmpIdIsNull() {
            addCriterion("operate_emp_id is null");
            return (Criteria) this;
        }

        public Criteria andOperateEmpIdIsNotNull() {
            addCriterion("operate_emp_id is not null");
            return (Criteria) this;
        }

        public Criteria andOperateEmpIdEqualTo(String value) {
            addCriterion("operate_emp_id =", value, "operateEmpId");
            return (Criteria) this;
        }

        public Criteria andOperateEmpIdNotEqualTo(String value) {
            addCriterion("operate_emp_id <>", value, "operateEmpId");
            return (Criteria) this;
        }

        public Criteria andOperateEmpIdGreaterThan(String value) {
            addCriterion("operate_emp_id >", value, "operateEmpId");
            return (Criteria) this;
        }

        public Criteria andOperateEmpIdGreaterThanOrEqualTo(String value) {
            addCriterion("operate_emp_id >=", value, "operateEmpId");
            return (Criteria) this;
        }

        public Criteria andOperateEmpIdLessThan(String value) {
            addCriterion("operate_emp_id <", value, "operateEmpId");
            return (Criteria) this;
        }

        public Criteria andOperateEmpIdLessThanOrEqualTo(String value) {
            addCriterion("operate_emp_id <=", value, "operateEmpId");
            return (Criteria) this;
        }

        public Criteria andOperateEmpIdLike(String value) {
            addCriterion("operate_emp_id like", value, "operateEmpId");
            return (Criteria) this;
        }

        public Criteria andOperateEmpIdNotLike(String value) {
            addCriterion("operate_emp_id not like", value, "operateEmpId");
            return (Criteria) this;
        }

        public Criteria andOperateEmpIdIn(List<String> values) {
            addCriterion("operate_emp_id in", values, "operateEmpId");
            return (Criteria) this;
        }

        public Criteria andOperateEmpIdNotIn(List<String> values) {
            addCriterion("operate_emp_id not in", values, "operateEmpId");
            return (Criteria) this;
        }

        public Criteria andOperateEmpIdBetween(String value1, String value2) {
            addCriterion("operate_emp_id between", value1, value2, "operateEmpId");
            return (Criteria) this;
        }

        public Criteria andOperateEmpIdNotBetween(String value1, String value2) {
            addCriterion("operate_emp_id not between", value1, value2, "operateEmpId");
            return (Criteria) this;
        }

        public Criteria andOperateTimeIsNull() {
            addCriterion("operate_time is null");
            return (Criteria) this;
        }

        public Criteria andOperateTimeIsNotNull() {
            addCriterion("operate_time is not null");
            return (Criteria) this;
        }

        public Criteria andOperateTimeEqualTo(Date value) {
            addCriterion("operate_time =", value, "operateTime");
            return (Criteria) this;
        }

        public Criteria andOperateTimeNotEqualTo(Date value) {
            addCriterion("operate_time <>", value, "operateTime");
            return (Criteria) this;
        }

        public Criteria andOperateTimeGreaterThan(Date value) {
            addCriterion("operate_time >", value, "operateTime");
            return (Criteria) this;
        }

        public Criteria andOperateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("operate_time >=", value, "operateTime");
            return (Criteria) this;
        }

        public Criteria andOperateTimeLessThan(Date value) {
            addCriterion("operate_time <", value, "operateTime");
            return (Criteria) this;
        }

        public Criteria andOperateTimeLessThanOrEqualTo(Date value) {
            addCriterion("operate_time <=", value, "operateTime");
            return (Criteria) this;
        }

        public Criteria andOperateTimeIn(List<Date> values) {
            addCriterion("operate_time in", values, "operateTime");
            return (Criteria) this;
        }

        public Criteria andOperateTimeNotIn(List<Date> values) {
            addCriterion("operate_time not in", values, "operateTime");
            return (Criteria) this;
        }

        public Criteria andOperateTimeBetween(Date value1, Date value2) {
            addCriterion("operate_time between", value1, value2, "operateTime");
            return (Criteria) this;
        }

        public Criteria andOperateTimeNotBetween(Date value1, Date value2) {
            addCriterion("operate_time not between", value1, value2, "operateTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table case_paid
     *
     * @mbg.generated do_not_delete_during_merge Thu Oct 18 15:28:41 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table case_paid
     *
     * @mbg.generated Thu Oct 18 15:28:41 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}