package com.atguigu.service;

import com.atguigu.bean.CaseLinkman;
import com.atguigu.bean.CaseLinkmanExample;
import com.atguigu.bean.CaseLinkmanWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CaseLinkmanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_linkman
     *
     * @mbg.generated Thu Oct 18 15:28:41 CST 2018
     */
    long countByExample(CaseLinkmanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_linkman
     *
     * @mbg.generated Thu Oct 18 15:28:41 CST 2018
     */
    int deleteByExample(CaseLinkmanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_linkman
     *
     * @mbg.generated Thu Oct 18 15:28:41 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_linkman
     *
     * @mbg.generated Thu Oct 18 15:28:41 CST 2018
     */
    int insert(CaseLinkmanWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_linkman
     *
     * @mbg.generated Thu Oct 18 15:28:41 CST 2018
     */
    int insertSelective(CaseLinkmanWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_linkman
     *
     * @mbg.generated Thu Oct 18 15:28:41 CST 2018
     */
    List<CaseLinkmanWithBLOBs> selectByExampleWithBLOBs(CaseLinkmanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_linkman
     *
     * @mbg.generated Thu Oct 18 15:28:41 CST 2018
     */
    List<CaseLinkman> selectByExample(CaseLinkmanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_linkman
     *
     * @mbg.generated Thu Oct 18 15:28:41 CST 2018
     */
    CaseLinkmanWithBLOBs selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_linkman
     *
     * @mbg.generated Thu Oct 18 15:28:41 CST 2018
     */
    int updateByExampleSelective(@Param("record") CaseLinkmanWithBLOBs record, @Param("example") CaseLinkmanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_linkman
     *
     * @mbg.generated Thu Oct 18 15:28:41 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") CaseLinkmanWithBLOBs record, @Param("example") CaseLinkmanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_linkman
     *
     * @mbg.generated Thu Oct 18 15:28:41 CST 2018
     */
    int updateByExample(@Param("record") CaseLinkman record, @Param("example") CaseLinkmanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_linkman
     *
     * @mbg.generated Thu Oct 18 15:28:41 CST 2018
     */
    int updateByPrimaryKeySelective(CaseLinkmanWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_linkman
     *
     * @mbg.generated Thu Oct 18 15:28:41 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(CaseLinkmanWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_linkman
     *
     * @mbg.generated Thu Oct 18 15:28:41 CST 2018
     */
    int updateByPrimaryKey(CaseLinkman record);
}