package com.atguigu.service;

import com.atguigu.bean.CaseBatch;
import com.atguigu.bean.CaseBatchExample;
import com.atguigu.bean.CaseBatchWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CaseBatchMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_batch
     *
     * @mbg.generated Thu Oct 18 15:28:41 CST 2018
     */
    long countByExample(CaseBatchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_batch
     *
     * @mbg.generated Thu Oct 18 15:28:41 CST 2018
     */
    int deleteByExample(CaseBatchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_batch
     *
     * @mbg.generated Thu Oct 18 15:28:41 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_batch
     *
     * @mbg.generated Thu Oct 18 15:28:41 CST 2018
     */
    int insert(CaseBatchWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_batch
     *
     * @mbg.generated Thu Oct 18 15:28:41 CST 2018
     */
    int insertSelective(CaseBatchWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_batch
     *
     * @mbg.generated Thu Oct 18 15:28:41 CST 2018
     */
    List<CaseBatchWithBLOBs> selectByExampleWithBLOBs(CaseBatchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_batch
     *
     * @mbg.generated Thu Oct 18 15:28:41 CST 2018
     */
    List<CaseBatch> selectByExample(CaseBatchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_batch
     *
     * @mbg.generated Thu Oct 18 15:28:41 CST 2018
     */
    CaseBatchWithBLOBs selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_batch
     *
     * @mbg.generated Thu Oct 18 15:28:41 CST 2018
     */
    int updateByExampleSelective(@Param("record") CaseBatchWithBLOBs record, @Param("example") CaseBatchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_batch
     *
     * @mbg.generated Thu Oct 18 15:28:41 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") CaseBatchWithBLOBs record, @Param("example") CaseBatchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_batch
     *
     * @mbg.generated Thu Oct 18 15:28:41 CST 2018
     */
    int updateByExample(@Param("record") CaseBatch record, @Param("example") CaseBatchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_batch
     *
     * @mbg.generated Thu Oct 18 15:28:41 CST 2018
     */
    int updateByPrimaryKeySelective(CaseBatchWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_batch
     *
     * @mbg.generated Thu Oct 18 15:28:41 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(CaseBatchWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_batch
     *
     * @mbg.generated Thu Oct 18 15:28:41 CST 2018
     */
    int updateByPrimaryKey(CaseBatch record);
}