package com.atguigu.service;

import com.atguigu.bean.CasePaid;
import com.atguigu.bean.CasePaidExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CasePaidMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_paid
     *
     * @mbg.generated Thu Oct 18 15:28:41 CST 2018
     */
    long countByExample(CasePaidExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_paid
     *
     * @mbg.generated Thu Oct 18 15:28:41 CST 2018
     */
    int deleteByExample(CasePaidExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_paid
     *
     * @mbg.generated Thu Oct 18 15:28:41 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_paid
     *
     * @mbg.generated Thu Oct 18 15:28:41 CST 2018
     */
    int insert(CasePaid record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_paid
     *
     * @mbg.generated Thu Oct 18 15:28:41 CST 2018
     */
    int insertSelective(CasePaid record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_paid
     *
     * @mbg.generated Thu Oct 18 15:28:41 CST 2018
     */
    List<CasePaid> selectByExampleWithBLOBs(CasePaidExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_paid
     *
     * @mbg.generated Thu Oct 18 15:28:41 CST 2018
     */
    List<CasePaid> selectByExample(CasePaidExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_paid
     *
     * @mbg.generated Thu Oct 18 15:28:41 CST 2018
     */
    CasePaid selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_paid
     *
     * @mbg.generated Thu Oct 18 15:28:41 CST 2018
     */
    int updateByExampleSelective(@Param("record") CasePaid record, @Param("example") CasePaidExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_paid
     *
     * @mbg.generated Thu Oct 18 15:28:41 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") CasePaid record, @Param("example") CasePaidExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_paid
     *
     * @mbg.generated Thu Oct 18 15:28:41 CST 2018
     */
    int updateByExample(@Param("record") CasePaid record, @Param("example") CasePaidExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_paid
     *
     * @mbg.generated Thu Oct 18 15:28:41 CST 2018
     */
    int updateByPrimaryKeySelective(CasePaid record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_paid
     *
     * @mbg.generated Thu Oct 18 15:28:41 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(CasePaid record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_paid
     *
     * @mbg.generated Thu Oct 18 15:28:41 CST 2018
     */
    int updateByPrimaryKey(CasePaid record);
}