package com.atguigu.service;

import com.atguigu.bean.Entrust;
import com.atguigu.bean.EntrustExample;
import com.atguigu.bean.EntrustWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EntrustMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entrust
     *
     * @mbg.generated Thu Oct 18 15:28:41 CST 2018
     */
    long countByExample(EntrustExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entrust
     *
     * @mbg.generated Thu Oct 18 15:28:41 CST 2018
     */
    int deleteByExample(EntrustExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entrust
     *
     * @mbg.generated Thu Oct 18 15:28:41 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entrust
     *
     * @mbg.generated Thu Oct 18 15:28:41 CST 2018
     */
    int insert(EntrustWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entrust
     *
     * @mbg.generated Thu Oct 18 15:28:41 CST 2018
     */
    int insertSelective(EntrustWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entrust
     *
     * @mbg.generated Thu Oct 18 15:28:41 CST 2018
     */
    List<EntrustWithBLOBs> selectByExampleWithBLOBs(EntrustExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entrust
     *
     * @mbg.generated Thu Oct 18 15:28:41 CST 2018
     */
    List<Entrust> selectByExample(EntrustExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entrust
     *
     * @mbg.generated Thu Oct 18 15:28:41 CST 2018
     */
    EntrustWithBLOBs selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entrust
     *
     * @mbg.generated Thu Oct 18 15:28:41 CST 2018
     */
    int updateByExampleSelective(@Param("record") EntrustWithBLOBs record, @Param("example") EntrustExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entrust
     *
     * @mbg.generated Thu Oct 18 15:28:41 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") EntrustWithBLOBs record, @Param("example") EntrustExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entrust
     *
     * @mbg.generated Thu Oct 18 15:28:41 CST 2018
     */
    int updateByExample(@Param("record") Entrust record, @Param("example") EntrustExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entrust
     *
     * @mbg.generated Thu Oct 18 15:28:41 CST 2018
     */
    int updateByPrimaryKeySelective(EntrustWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entrust
     *
     * @mbg.generated Thu Oct 18 15:28:41 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(EntrustWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entrust
     *
     * @mbg.generated Thu Oct 18 15:28:41 CST 2018
     */
    int updateByPrimaryKey(Entrust record);
}