package com.atguigu.service;

import com.atguigu.bean.SysPosition;
import com.atguigu.bean.SysPositionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysPositionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_position
     *
     * @mbg.generated Thu Oct 18 15:28:41 CST 2018
     */
    long countByExample(SysPositionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_position
     *
     * @mbg.generated Thu Oct 18 15:28:41 CST 2018
     */
    int deleteByExample(SysPositionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_position
     *
     * @mbg.generated Thu Oct 18 15:28:41 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_position
     *
     * @mbg.generated Thu Oct 18 15:28:41 CST 2018
     */
    int insert(SysPosition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_position
     *
     * @mbg.generated Thu Oct 18 15:28:41 CST 2018
     */
    int insertSelective(SysPosition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_position
     *
     * @mbg.generated Thu Oct 18 15:28:41 CST 2018
     */
    List<SysPosition> selectByExample(SysPositionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_position
     *
     * @mbg.generated Thu Oct 18 15:28:41 CST 2018
     */
    SysPosition selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_position
     *
     * @mbg.generated Thu Oct 18 15:28:41 CST 2018
     */
    int updateByExampleSelective(@Param("record") SysPosition record, @Param("example") SysPositionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_position
     *
     * @mbg.generated Thu Oct 18 15:28:41 CST 2018
     */
    int updateByExample(@Param("record") SysPosition record, @Param("example") SysPositionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_position
     *
     * @mbg.generated Thu Oct 18 15:28:41 CST 2018
     */
    int updateByPrimaryKeySelective(SysPosition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_position
     *
     * @mbg.generated Thu Oct 18 15:28:41 CST 2018
     */
    int updateByPrimaryKey(SysPosition record);
}