package com.atguigu.service;

import com.atguigu.bean.SysUserRoleRelationExample;
import com.atguigu.bean.SysUserRoleRelationKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysUserRoleRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_role_relation
     *
     * @mbg.generated Thu Oct 18 15:28:41 CST 2018
     */
    long countByExample(SysUserRoleRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_role_relation
     *
     * @mbg.generated Thu Oct 18 15:28:41 CST 2018
     */
    int deleteByExample(SysUserRoleRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_role_relation
     *
     * @mbg.generated Thu Oct 18 15:28:41 CST 2018
     */
    int deleteByPrimaryKey(SysUserRoleRelationKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_role_relation
     *
     * @mbg.generated Thu Oct 18 15:28:41 CST 2018
     */
    int insert(SysUserRoleRelationKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_role_relation
     *
     * @mbg.generated Thu Oct 18 15:28:41 CST 2018
     */
    int insertSelective(SysUserRoleRelationKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_role_relation
     *
     * @mbg.generated Thu Oct 18 15:28:41 CST 2018
     */
    List<SysUserRoleRelationKey> selectByExample(SysUserRoleRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_role_relation
     *
     * @mbg.generated Thu Oct 18 15:28:41 CST 2018
     */
    int updateByExampleSelective(@Param("record") SysUserRoleRelationKey record, @Param("example") SysUserRoleRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_role_relation
     *
     * @mbg.generated Thu Oct 18 15:28:41 CST 2018
     */
    int updateByExample(@Param("record") SysUserRoleRelationKey record, @Param("example") SysUserRoleRelationExample example);
}